### ISSUE TITLE
Request: Spinning version of icons

### ISSUE THREAD

**Issue by bmcbarron** [microsoft/vscode-codicons#100]
**Is your icon request related to a problem? Please describe.**
The [documentation](https://code.visualstudio.com/api/references/icons-in-labels) suggests that spinning icon variants should be accessible to extensions. However, I do not see the necessary css in this package that implements spinning.

**Describe the solution you'd like**
This [codicon-modifiers.css](https://github.com/microsoft/vscode/blob/21da6eeafa5cac8ff18ef0e1a3fb256625db21ce/src/vs/base/browser/ui/codicons/codicon/codicon-modifiers.css) file seems to include the necessary code. If that code were added to this package, it would solve my issue and make the documentation more accurate.

**Describe alternatives you've considered**
For now, I'm copying and pasting the content of `codicon-modifiers.css` into my code. Other projects [have also done this](https://github.com/search?q=codicon-spin&type=code). If that's the desired solution, consider adding the necessary (short) snippet to the documentation of this package (and/or to [the example](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-codicons-sample)).

**Comment by misolori** [comment]
See this issue for the discussion https://github.com/microsoft/vscode/issues/112298 We decided that it was ultimately a bad idea to allow any icon to spin so we've scoped it down to specific icons (like sync/loading/gear). Are there other icons where you'd like to have animations supported?

**Comment by bmcbarron** [comment]
I did see that issue. My proposed solution (adding codicon-modifiers.css to this package), only enables spinning for 4 icons. In particular, this is the code that vs code uses internally. My suggestion is that the same 4 spinning variations be made available (officially) to extensions as well.

**Comment by bmcbarron** [comment]
Wow, fast work! Thanks so much!
