### ISSUE TITLE
add icon is not centered

### ISSUE THREAD

**Issue by taylorcode** [microsoft/vscode-codicons#108]
**Describe the bug**
The "add" icon is not centered within the viewbox. The viewbox is 16x16 and the icon is 13x13. There is 1px of space on the top and left edge, and 2px on the right and bottom.

<img width="539" alt="original" src="https://user-images.githubusercontent.com/6465562/166122929-524878b3-9bda-4b54-9deb-fd98a12f6857.png">

**To Reproduce**
Open the icon in a design tool which supports svg, or a browser.

**Expected behavior**
There should be 1.5px of space around the icon.

<img width="536" alt="fixed" src="https://user-images.githubusercontent.com/6465562/166122932-05f4b9c6-7a1c-49cc-8958-148bd7e8578a.png">

**Environment**
Previewed in Figma

**Additional context**
I discovered this issue while trying to use the react-icons package. https://react-icons.github.io/react-icons/icons?name=vsc

**Comment by misolori** [comment]
Thanks for the feedback. This is actually intentional as we want to keep the icon aligned to the pixel grid to avoid pixelation as we have a lot of users on non-hdpi screens using vscode. We always strive to keep things aligned to the grid wherever possible.
