### ISSUE TITLE
Some icons aren't rendering in the plugin

### ISSUE THREAD

**Issue by plainspace** [microsoft/vscode-codicons#11]
Uninstalled and reinstalled the plugin as well as the font files. E.g. `account` and `bell dot` are not rendering. Seems to be affecting ~10% of icons.

<img width="369" alt="Screen Shot 2020-04-06 at 16 44 29" src="https://user-images.githubusercontent.com/24152/78615289-ec315300-7825-11ea-9737-87de75f0626b.png">

**Comment by misolori** [comment]
@plainspace have you tried rebooting your machine after installing the new font? Often times there are icon caches that don’t get automatically cleared (I have to do this every time we update the icon don’t).

**Comment by plainspace** [comment]
You learn something new every day. Thanks mate.

**Comment by daviddossett** [comment]
@liupeng0913 is this happening in the plugin? I see all icons rendering on my end:

<img width="454" alt="CleanShot 2023-06-30 at 09 43 19@2x" src="https://github.com/microsoft/vscode-codicons/assets/25163139/dfc734b6-acdd-4d5c-91bf-18d2bff9f13f">

**Comment by liupeng0913** [comment]
> @liupeng0913 is this happening in the plugin? I see all icons rendering on my end:
> 
> <img alt="CleanShot 2023-06-30 at 09 43 19@2x" width="454" src="https://user-images.githubusercontent.com/25163139/250148169-dfc734b6-acdd-4d5c-91bf-18d2bff9f13f.png">

Maybe my description wasn't clear enough. I am developing a vscode extension, and I use the codicons icon in it. When I package the extension and install it in vscode, the icon appears as a white box.

**Comment by daviddossett** [comment]
Are you installing the codicons library via npm? I don't know how to repro if you're doing something custom like this:

> I put the codicon.css file into my webview folder and packaged my extension to .vsix file

**Comment by liupeng0913** [comment]
> Are you installing the codicons library via npm? I don't know how to repro if you're doing something custom like this:
> 
> > I put the codicon.css file into my webview folder and packaged my extension to .vsix file

Yes,I installing codicons library via npm as devDependencies like codicon sample project. And when i packing it to extension I found the codion npm package not in the extension ( this maybe right, cause it's devDependence), and the place where the icon should appear is blank and nothing. 
But as far as I understand, if codicon is to work in extensoin, it should also be packaged in extension. So I put the codicons source file into extension ( that is the customization you mentioned ), and here the white box appear.This is where I get confused
