### ISSUE TITLE
blank codicon

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-codicons#110]
_Originally posted by @lovettchris_ in https://github.com/microsoft/vscode/issues/150481

Sometimes when you are building a custom UI in a vscode extension webview with codicons, it is handy to have a "blank" icon that is the same size as all other codicons so that you can get the correct alignment without having to hack a css style to create spacing the exact same number of pixels as the codicons.  For example, this dropdown filter widget has optional checkmarks:

![image](https://user-images.githubusercontent.com/18707114/170553479-b53a36ac-cde6-4566-a29e-6789e353b9c3.png)

![image](https://user-images.githubusercontent.com/18707114/170553458-5b76820e-e9b6-453f-b77a-73f0ef7c080e.png)

To make those checkmarks & text labels align correctly we had to do this ugly CSS hack:

```css
.codicon-blank {
    width: 20px;
    height: 16px;
}
```

it would be way better if you provided this CSS style in your codicon library...

**Comment by misolori** [comment]
@lovettchris curious if you are using the [VS Code Webview Toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit)? 

I'd imagine we could support this as a modifier, similar to https://github.com/microsoft/vscode-codicons/issues/100

**Comment by lovettchris** [comment]
Sure a modifier setting opactity to zero might be one way to do it.  We are not using the webview toolkit, this is the code https://github.com/leanprover/vscode-lean4, the webview lives in the [infoview](https://github.com/leanprover/vscode-lean4/blob/master/lean4-infoview/package.json) folder.  We are using React and the popups we do are trying to be similar UI to the tooltips in the VS code text editor using React-popper components.

**Comment by misolori** [comment]
Decided to add a regular blank icon instead and also added a `.codicon-modifier-hidden` to hide any icon as well. Hope that helps your situation.

**Comment by lovettchris** [comment]
Thanks @misolori, you rock!
