### ISSUE TITLE
Require an icon for 'build'

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-codicons#111]
**Is your icon request related to a problem? Please describe.**
I would like an icon for the action `build`(or `compile`). So far, I did not find a suitable icon for this action.

This icon can be used in a lot of extensions since build/compile is a very common action in different languages.

**Describe the solution you'd like**
Below are the icons for build in different IDEs:

intelliJ:
![image](https://user-images.githubusercontent.com/6193897/172156093-5ff78dc4-cb20-4e13-86eb-d381f215efb0.png)

Eclipse:
![image](https://user-images.githubusercontent.com/6193897/172156117-bdb8055d-feff-41f7-8574-9b52fd495da9.png)

Visual Studio:
![image](https://user-images.githubusercontent.com/6193897/172156153-cffe3e5a-1613-4599-b3dd-4595586d28e9.png)

Personally, I prefer the hammer one.

**Comment by misolori** [comment]
We use the `tools` icon for build tasks, can you use the same icon?

<img width="140" alt="CleanShot 2022-06-06 at 09 30 12@2x" src="https://user-images.githubusercontent.com/35271042/172204025-c94109de-8d20-454a-9015-ebe5fe4eb201.png">

<img width="180" alt="CleanShot 2022-06-06 at 09 32 35@2x" src="https://user-images.githubusercontent.com/35271042/172204360-2f794b3f-64de-498b-b952-1460ed57fff0.png">

**Comment by jdneo** [comment]
Thank you @misolori, 

I noticed this icon before and was thinking that it's an icon for general tasks (not specific enough as a build task).

It's just my personal feeling, maybe it's not true for other users :)

I can first use this icon for build tasks and see if there are any feedbacks in the future.

**Comment by jdneo** [comment]
Hi @miguelsolorio

We use the `tools` icon to represent as the `build` action.
![image](https://user-images.githubusercontent.com/6193897/216930377-403bfbe7-2932-4e1f-a44d-1479d8ea671a.png)

Recently, we received customer feedback saying `the Icon for "Rebuild all" Miss leads me a bit. It Looks more like a Config button`.

Will you reconsider to introduce a new icon for `build`? 😁
