### ISSUE TITLE
Add a sourcemap and disable sourcemap button

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#115]
**Is your icon request related to a problem? Please describe.**

In JS debug, we added new functionality to disable and re-enable sourcemaps. (Posted in the #ux channel)

**Describe the solution you'd like**

Having a "map" and "disable map" icon

**Describe alternatives you've considered**

We use the compass icon today, but a map would be more explicit.

**Comment by misolori** [comment]
we could alternate between two icons?

<img width="246" alt="CleanShot 2022-06-15 at 15 49 16@2x" src="https://user-images.githubusercontent.com/35271042/173954997-6b6b6947-55f0-4e38-87c1-0d118a69ce9d.png">

**Comment by connor4312** [comment]
That could work!

**Comment by misolori** [comment]
Added these two

<img width="277" alt="CleanShot 2022-06-17 at 11 53 22@2x" src="https://user-images.githubusercontent.com/35271042/174385680-d1aa2faa-bb02-41ac-8aae-012972851bea.png">
