### ISSUE TITLE
Feature Request: Provide Icons As PNG

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-codicons#119]
Currently, they are only available as SVG or through the font.
If they would be available is PNG, they could be linked in markdown, e.g. in the doc comments of the Codicon class in VS Code. Then a preview would show in auto-complete.

**Comment by misolori** [comment]
Why can't you use the svgs or the icon font? You can always embed an SVG as an image. Not a big fan of needing to generate image assets as it removes the scalability and creates rasterization but open to learning more about the use case.

**Comment by hediet** [comment]
Because it doesn't work:

![image](https://user-images.githubusercontent.com/2931520/175292479-d8010f79-f3ad-4faf-9ddb-eb42e47c30e6.png)

>  Not a big fan of needing to generate image assets

It should be easy to setup a github action that does this automatically (and pushes the result to a separate branch, maybe even using gh pages).

**Comment by misolori** [comment]
How will image previews work with different themes since icons that are exported will have a single color?

**Comment by hediet** [comment]
> I wonder if we can support the $(icon) syntax in the jsdocs, similar to other parts in the editor? We support this in regular markdown hovers

Would be useful here. But very specific to VS Code.

> How will image previews work with different themes since icons that are exported will have a single color?

Not at all, the PNG should have a background color. It's just a preview to make the Codicon class more useful, especially since we have the ability to show images in markdown.

**Comment by misolori** [comment]
> Would be useful here. But very specific to VS Code.

Is this not the main motivation to use pngs? Or am I missing something?

> If they would be available is PNG, they could be linked in markdown, e.g. in the doc comments of the Codicon class in VS Code. Then a preview would show in auto-complete.

**Comment by misolori** [comment]
I'm still not convinced that adding PNGs is the right solution nor would it look great as they become rasterized, aren't scalable with themes, and would significantly increase the package size for most who wouldn't use it. Not to mention that we spent a significant amount of effort a few years ago to move away from using PNGs in the product. We currently support using codicons in our rich hovers and don't see why extending that support for this use case is any different.

<img width="556" alt="CleanShot 2022-06-24 at 07 07 37@2x" src="https://user-images.githubusercontent.com/35271042/175552793-2e2a0885-4d8b-4116-8371-981b3c4694c5.png">

**Comment by Tyriar** [comment]
Personal opinion: Code comments shouldn't have icons or any non-ascii images. If you just want a quick way to view all the icons during development the `Terminal: Change Icon` command is good for that:

![image](https://user-images.githubusercontent.com/2193314/185190234-0a56604c-92ab-407e-ba1e-9515f40cda3f.png)

**Comment by misolori** [comment]
Will close this issue as we don't plan on doing this
