### ISSUE TITLE
Icon request: Terminal shell integration command decorations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-codicons#126]
**Is your icon request related to a problem? Please describe.**

- terminal-decoration-incomplete (previously "default" or "placeholder" but incomplete is probably best)
- terminal-decoration-success
- terminal-decoration-error
- terminal-decoration-mark

See https://github.com/microsoft/vscode/issues/156503

cc @meganrogge

**Comment by misolori** [comment]
Ah, so we simply need to add new aliases for these items? That should be a pretty easy ask.

**Comment by Tyriar** [comment]
Yep that's all for this

**Comment by misolori** [comment]
Here is the mapping I have (we also recently updated the naming for filled vs outline to default to outline and call out 'filled' versions), can you help fill in the gaps?

- `terminal-decoration-incomplete` => `circle`
- `terminal-decoration-success` => `circle-filled`
- `terminal-decoration-error` => `error-small`
- `terminal-decoration-mark` => `???`

**Comment by meganrogge** [comment]
`terminal-decoration-mark`=> `circle-small-filled`
