### ISSUE TITLE
Add codicon to record profiles

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#13]
There's this icon 

![](https://user-images.githubusercontent.com/35271042/80632316-f3eeac80-8a0b-11ea-90c6-d6374d15dd8f.png)

I think it should be a codicon so that we can have its style match the user's theme color (if I provide an svg icon in js-debug, it's a fixed color).

**Comment by misolori** [comment]
Not sure how this was missed but I'll definitely add it.

**Comment by connor4312** [comment]
Oh, also, if we can get the "profiling" icon at the same time that would be awesome. I have an svg there now which looks _decent_ but matching the theme color precisely would be even better.

**Comment by misolori** [comment]
This was added via https://github.com/microsoft/vscode-codicons/commit/834f35ab47a04cf60eb5a51b1c2dab791d2d576c

![image](https://user-images.githubusercontent.com/35271042/84536806-73c29480-aca3-11ea-8917-d7ddaeb52409.png)
