### ISSUE TITLE
Duplicated code points for bell-slash and map

### ISSUE THREAD

**Issue by kascote** [microsoft/vscode-codicons#130]
**Describe the bug**
The last release is using the same code for different icons
```
bell-slash,,EC05
map,,EC05
```

**To Reproduce**
on [this commit](https://github.com/microsoft/vscode-codicons/commit/a10a2c46730dc0b8d23906504060a68434880370#diff-efccf4bc95f9b7eb50cd2269566714720de445477337377888b8b9f31c5170b0
) sets `bell-slash`

on [this commit](https://github.com/microsoft/vscode-codicons/commit/33bed29edb3afb2eef6a9aa56fb2d68238956267#diff-efccf4bc95f9b7eb50cd2269566714720de445477337377888b8b9f31c5170b0) sets `map`

**Expected behavior**
Both icons must have different code points

**Screenshots**
<img width="256" alt="Screen Shot 2022-08-03 at 21 16 58" src="https://user-images.githubusercontent.com/9757/182736663-e3feb423-99d7-43f1-baa5-f1790bf54d75.png">

**Environment**
 - OS: Mac, Windows
 - VS Code Version not used

I'm checking on the terminal.
The other icons on this release are ok.
<img width="368" alt="Screen Shot 2022-08-03 at 21 19 09" src="https://user-images.githubusercontent.com/9757/182736882-4cda91c0-3d50-492d-b665-6f9afdb1e9cc.png">

**Comment by misolori** [comment]
Thanks for filling the issue! A few questions:

> The last release is using the same code for different icons

When you say last release, do you mean the codicons npm package or the VS Code release? What version are you on?

Also, when looking at our [csv export](https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.csv), I am not seeing the same values as you are. Where are you seeing those icons?

<img width="460" alt="CleanShot 2022-08-03 at 18 39 11@2x" src="https://user-images.githubusercontent.com/35271042/182744565-108295be-f460-4f7d-89d2-268e35ec3d0e.png">

<img width="464" alt="CleanShot 2022-08-03 at 18 39 38@2x" src="https://user-images.githubusercontent.com/35271042/182744618-94576310-8984-44cf-9351-4f1bd217836f.png">

**Comment by kascote** [comment]
sorry, my bad 🤦🏼 ... I was checking an old commit and not viewing the last one.

**Comment by misolori** [comment]
No worries, often times when there is a mixup like that in a commit it's usually fixed in another commit. Always checkout the latest in `dist` to see what the real values point to.
