### ISSUE TITLE
Icon request: Fuzzy search

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-codicons#132]
**Is your icon request related to a problem? Please describe.**

We want an icon to signify the concept of "fuzzy search" for the vscode terminal run recent command search mode (and potentially other quick picks) to replace this ugly button:

![image](https://user-images.githubusercontent.com/2193314/185189246-d9a4524f-d879-46bd-97b5-1498b7696f0f.png)

https://github.com/microsoft/vscode/issues/156322

**Describe the solution you'd like**

I think some icon like this is the best fit so far:

![image](https://user-images.githubusercontent.com/2193314/185189327-3fb4ec2b-7b6d-4a45-a783-7df7c1827cc5.png)

**Describe alternatives you've considered**

Some brainstorming:

![image](https://user-images.githubusercontent.com/2193314/185189406-e7ab85c4-900e-40c4-9fee-a1089d133c50.png)
![image](https://user-images.githubusercontent.com/2193314/185189436-ab882a63-dd3d-427d-a6ca-a1d79ac5cb2f.png)

**Comment by misolori** [comment]
How's this? Had to make the magnifying glass a little shorter to fit the squiggle:

<img width="376" alt="CleanShot 2022-08-17 at 13 20 52@2x" src="https://user-images.githubusercontent.com/35271042/185235408-e5b6f4eb-6e8a-4dfb-bd3a-3f7954d66438.png">


<img width="309" alt="CleanShot 2022-08-17 at 13 20 30@2x" src="https://user-images.githubusercontent.com/35271042/185235310-38d29fd1-0f1b-4d4d-8e2b-d2f8c18b411d.png">

<img width="60" alt="CleanShot 2022-08-17 at 13 20 41@2x" src="https://user-images.githubusercontent.com/35271042/185235343-010003ae-a74c-4532-a71c-aec95a3671b3.png">

**Comment by Tyriar** [comment]
Looks good 👍
