### ISSUE TITLE
Request a docker like icon

### ISSUE THREAD

**Issue by jroman-sh** [microsoft/vscode-codicons#135]
I know that docker does not want their icon to be use. But could there be a docker like icon. Simply a kind of whale with some squares on top that resembles to the docker icon. It could be named `container` or `whale-container` or something like that.

**Comment by misolori** [comment]
> Simply a kind of whale with some squares on top that resembles to the docker icon

I appreciate in trying to get creative here but anything that mimics the Docker logo would be grounds of copyright infringement so I'd rather not go down that route. you can use the `symbol-method` icon

<img width="145" alt="CleanShot 2022-08-29 at 10 22 34@2x" src="https://user-images.githubusercontent.com/35271042/187260129-c5627d20-b56e-4f54-83a5-807536a7d831.png">
