### ISSUE TITLE
Pieces of the `remote-explorer` icon appears blurry

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-codicons#14]
First of all, thank you for publishing this repo. It's a real time-saver to be able to use these icons on our extensions 👏 

About the issue, I've noticed that some pieces of the `remote-explorer` icon appears blurry, compared to other icons, like `folder` and `root-folder`, which has sharper lines.

The `remote-explorer` icon is a monitor in the back with a remote symbol inside a small circle, in front. You may notice that the _monitor_ is blurry, specially with zoom level 0. 

I added a few screenshots, dark and light themed, with zoom level 0 and 3.

![Screen Shot 2020-05-13 at 01 13 46](https://user-images.githubusercontent.com/3781424/81770596-2a6e0200-94b7-11ea-9951-6ef01b0feec7.png)
![Screen Shot 2020-05-13 at 01 14 02](https://user-images.githubusercontent.com/3781424/81770600-2b9f2f00-94b7-11ea-8a7b-a300b0f9f2c2.png)
![Screen Shot 2020-05-13 at 01 14 39](https://user-images.githubusercontent.com/3781424/81770603-2d68f280-94b7-11ea-95ff-648033fa1342.png)
![Screen Shot 2020-05-13 at 01 14 23](https://user-images.githubusercontent.com/3781424/81770601-2c37c580-94b7-11ea-9061-6ccec22ae219.png)

Also, the remote symbol (><) inside the small circle is hard to distinguish, but in this case, not because is blurry, but small. I'm not sure, but maybe thicker lines would give a better result.

Thank you

**Comment by misolori** [comment]
Thanks for the compliment!

So there is certain set of icons that were designed to only be used in the activity bar with a slightly thicker stroke (1.5px) compared to the regular icons (1px), which means it will be off the pixel grid. The remote explorer is one of them but this also applies to the files, search, source control, etc. If you try using the `vm` you’ll notice this one is not pixelated. 

I’ll see if I can bump the stroke on the indicator inside, but I’m fairly certain that we won’t be able to solve the pixelation issue as last time we tried the 1px stroke in the activity bar they were too think. But I’ll definitely give it a shot.

**Comment by alefragnani** [comment]
Hi @misolori ,

I was suspicious about that, because I only saw that icon being used in the Side Bar. And I totally understand the difficulties on using the same icon in bottom places.

My initial ideas wasn’t to use this icon, because the intention was to have a remote _folder_ not _computer_, but it isn’t available in codicons. And I really wanted to embrace codicons on my extension, replacing their SVGs (which BTW are from/based on the other [figma collection](https://www.figma.com/community/plugin/786075219184960694/Visual-Studio-Code-Icons) you published 😁   ).

Thank you

**Comment by misolori** [comment]
I've added `vm-connect` in the [June release](https://code.visualstudio.com/updates/v1_47#_new-codicon-icons) that should fit on a 16x16 square:

![image](https://user-images.githubusercontent.com/35271042/87335728-9b508b00-c4f5-11ea-965b-9072a3eb57db.png)

**Comment by alefragnani** [comment]
Thank you @misolori , I've noted right after it's launch, and already opened an issue on my Project Manager extension to use it (https://github.com/alefragnani/vscode-project-manager/issues/396). 

I also added an issue on a NPM package that I've created (https://www.npmjs.com/package/vscode-ext-codicons), which exports all codicons/themeicons, for easier use.

Thank you for the update 👍

**Comment by misolori** [comment]
Very cool, we also have an npm package of this repo as well: https://www.npmjs.com/package/vscode-codicons

**Comment by alefragnani** [comment]
That's the repo I use as _source_ to know the icons and their mappings 😄
