### ISSUE TITLE
Request to add new icon to Codicon library

### ISSUE THREAD

**Issue by stariolo** [microsoft/vscode-codicons#148]
Hi! 
We would like to contribute a new icon to the codicon library and we want to know what is the best way to do it and what do you need from us

### Why do we want to do this?
When users review code inside Google they usually interact a lot with comments to provide feedback to authors about their code. 
Comments are usually written and saved but not published until the end of this user journey. Users need time to add, edit, delete comments while they are reviewing/modifing code to send them all at once. 
We offer 3 comment statuses:

- Published and Unresolved

- Published and Resolved

- Draft (Saved but not published)

Those 3 statuses are represented across the interface with icons so users can screen and recognize them quickly in the UI.

On Cider V, we are currently using the pencil icon to represent “draft” status, but the icon doesn't represent the context properly, creating confusion with other concepts such as modified/draft: code, line, comments or file.

- **Source Control panel:**
<img width="795" alt="Screenshot 2022-11-09 at 14 51 01" src="https://user-images.githubusercontent.com/96111020/201349699-37045044-ecd4-4472-833c-d5349f031587.png">

- **Status bar:**
<img width="409" alt="Screenshot 2022-11-09 at 14 51 52" src="https://user-images.githubusercontent.com/96111020/201349878-b0310dee-2da6-49ca-a666-529c8e37f52c.png">

- **Indicator in line number of  the editor:**
<img width="438" alt="Screenshot 2022-11-09 at 14 53 19" src="https://user-images.githubusercontent.com/96111020/201349999-aa637bdf-7eca-4c18-ab8b-95ea55736a94.png">

### Proposal
We would like to contribute to the codicon library with a “draft” comments icon. This will clarify the context of the icon and the community can useit for other types of status such as: Draft Comments/Chats, Modified Comments/Chats, etc.
The style applied on both options follow the patterns on how other icons are treated in [Codicon Library](https://microsoft.github.io/vscode-codicons/dist/codicon.html) (like: save-as, new-folder, report icon). The team created two proposals with that in mind:

<img width="972" alt="Screenshot 2022-11-09 at 15 07 04" src="https://user-images.githubusercontent.com/96111020/201350078-72d10e53-52cc-43b0-81f6-e49e5d3828a7.png">

The UX Google team would love to hear your feedback to continue working on this.
Thanks for your time.

**Comment by daviddossett** [comment]
I also wonder if it's worth exploring a dotted stroke concept to represent draft/unfinished like these other codicons. My only concern with the pencil is that it conveys an "edit" action/verb rather than a state. 

I can help get the icon added once we've arrived at a design we like 👍 

<img width="282" alt="CleanShot 2022-11-11 at 09 42 31@2x" src="https://user-images.githubusercontent.com/25163139/201398502-a84c21db-2911-409b-ba6a-8c6990666508.png">

**Comment by laurentlb** [comment]
@alexr00 Yes, I think it would be useful to have this information in the comment thread.

On our side, we have two fields:
- resolved / unresolved
- published / draft

As it's orthogonal, I wouldn't add it to the CommentThreadState enum.

(for the icon, we could imagine an icon for the state "unresolved+draft", but that doesn't seem very important to us)

**Comment by stariolo** [comment]
I like the idea of dotted stroke concept to represent draft/unfinished
<img width="198" alt="Screenshot 2022-11-11 at 19 31 15" src="https://user-images.githubusercontent.com/96111020/201407370-8fa8cec6-37c2-4617-a576-493aa3991f47.png">

**Comment by albertelo** [comment]
Thanks Mariana! @alexr00 & @daviddossett let us know if you need more explorations or if we need to refine the current ones

**Comment by daviddossett** [comment]
I like the proposal above! Just catching up from vacation but I'll tag you both in the PR to add this icon this week.

**Comment by stariolo** [comment]
Thank you! Do you need a file source?

Thanks

**Comment by daviddossett** [comment]
@stariolo that wouldn't hurt! Is your example based off the original `comment` codicon? If so, it could probably be easily merged into the codicons library. If not, I can recreate it.

**Comment by albertelo** [comment]
@daviddossett following up here: did you file the PR? anything else you might need from our end? Thank you!

**Comment by daviddossett** [comment]
Added `comment-draft` via #152 🙏
