### ISSUE TITLE
Inverted fill/stroke on some icons in `npm i vscode-codicons`

### ISSUE THREAD

**Issue by jeffersonking** [microsoft/vscode-codicons#15]
I installed the icons via `npm i vscode-codicons`. Some of the icons in the TTF are inverted and look like this:

![Screen Shot 2020-06-06 at 10 29 50 PM](https://user-images.githubusercontent.com/3452831/83961162-56c23780-a845-11ea-82db-cafd79400cd2.png)

The TTF file in this repo is correct. Previous versions of the TTF file are also correct. Would it be possible update the `npm` version of the TTF file to fix this issue? Thanks!

**Comment by misolori** [comment]
I actually was not aware that there was an npm package, we (Microsoft) do not own that so there is not anything we can do. I'll look into seeing if we can take over the ownership of that package. Thanks.

**Comment by jeffersonking** [comment]
Thanks @misolori. If you could publish on NPM an official @microsoft that would be very useful for us. We consume it here https://github.com/microsoft/sarif-vscode-extension. Our team has experience publishing to NPM and would be happy to help.

**Comment by misolori** [comment]
@jeffersoneagley I requested access to the npm package and am now a maintainer so I'll be pushing updates to the package as well. New version is now out https://www.npmjs.com/package/vscode-codicons/v/0.0.2

**Comment by jeffersonking** [comment]
Awesome. Thanks!

**Comment by jeffersonking** [comment]
Verified as fixed.
