### ISSUE TITLE
Icon buttons size problem inside inputs

### ISSUE THREAD

**Issue by AlencarGabriel** [microsoft/vscode-codicons#158]
![image](https://user-images.githubusercontent.com/10109480/213568961-af97a176-2e18-4ab1-b640-947829b00ec3.png)
latest version (0.0.32)

![image](https://user-images.githubusercontent.com/10109480/213568552-9f30e0f9-5fe7-43bb-b2b8-3ff7e696f7f7.png)
version 0.0.26

I noticed that in the latest version, icon buttons inside textboxes are becoming misaligned and bigger than they used to be.

I'm using the @vscode/webview-ui-toolkit components in webview. Just downgrading the vscode-codicons version the problem stops occurring.

ps.: this problem happens with other icons as well

**Comment by daviddossett** [comment]
Are you only seeing this in the webview toolkit? cc @hawkticehurst for toolkit-related issues.

I'm not seeing this in VS Code's core UI, so trying to understand what is causing this.

**Comment by AlencarGabriel** [comment]
@daviddossett  the problem actually happens in the webview toolkit. But only in newer versions of vscode-codicons.

If the problem really is in the toolkit, can you transfer this problem there?
