### ISSUE TITLE
Filled thumbs up and down

### ISSUE THREAD

**Issue by albertelo** [microsoft/vscode-codicons#163]
The thumbs up / down icons are available as outlines: 
![Screenshot 2023-02-03 at 12 22 53](https://user-images.githubusercontent.com/26898237/216591518-80dc0f2d-cd55-40bd-856f-ae3bf37b4567.png)

Can we have the same icons but filled? Similarly to what the filter icon offers: 
![Screenshot 2023-02-03 at 12 24 05](https://user-images.githubusercontent.com/26898237/216591671-e31b703f-e386-47bc-a2d8-3d7f5d85caf8.png)

**Comment by drob** [comment]
I took a stab at this just last night. https://github.com/microsoft/vscode-codicons/pull/162

Happy to help wedge this into a project that uses codicons if they don't get around to adding them.

**Comment by albertelo** [comment]
@daviddossett Hi David, wanted to check-in here to see if it was possible to add this if it wasn't done so yet. Thanks!

**Comment by daviddossett** [comment]
Merged. Thank you @drob!
