### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by dsmmcken** [microsoft/vscode-codicons#169]
There hasn't been a new package published to npm for 8 months, but I see there's lots of new icons and activity.

Can publishing new releases when icons are added be resumed please?

**Comment by daviddossett** [comment]
Thanks for the ping—I'll do so when I'm back from vacation.

**Comment by TheFuseGamer** [comment]
I need some of the new icons as well. A new release would be appreciated.

**Comment by daviddossett** [comment]
Published 0.0.33
- https://www.npmjs.com/package/@vscode/codicons
- https://github.com/microsoft/vscode-codicons/releases/tag/0.0.33
