### ISSUE TITLE
[Icon Request] Logic Apps Custom Code icon

### ISSUE THREAD

**Issue by Nolan-Can** [microsoft/vscode-codicons#171]
**Is your icon request related to a problem? Please describe.**
Logic apps is looking for an icon to use for an upcoming feature in its VSCode extension. After browsing existing icons, we weren't able to find one that would correlate to this action. 

**Describe the solution you'd like**
We'd like help in designing and approving an icon for this feature.

**Describe alternatives you've considered**
Initial discovery lead me to discover these icons for potential use:
<img width="817" alt="image" src="https://user-images.githubusercontent.com/101218935/233134570-47a02745-eb6f-431e-8dd4-258821de5fd2.png">

Upon getting feedback from product team, refined and tried to find more options:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/101218935/233134737-e549cb3a-4930-44af-9735-ceac525e1664.png">

Product team wanted to move forward with a hybrid of the Azure Workflow icon and the Fluent/Flash Add icon, to which I created a few variations of below. Additionally, had conversations with David Dossett and Kaitlin Brooks, who informed us of more of the VSCode iconography style guides leading to this issue creation.
<img width="227" alt="image" src="https://user-images.githubusercontent.com/101218935/233135369-99135908-4643-496f-a596-c1c201f20029.png">

**Comment by daviddossett** [comment]
I would say these are so specific to Azure that it likely doesn't make a lot of sense to put them in the core VS Code icon library. In these situations, extensions can contribute their own custom icons, similar to what Azure has done in the past per your pictures (although I would have recommended that they use the VS Code monoline style instead). 

David H has made custom icons for VS Code extensions in the past—I'd say he would be the next person to talk to here.
