### ISSUE TITLE
Icons for remote connection state: Slow

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-codicons#178]
Refs: https://github.com/microsoft/vscode/issues/178553

As a user I want an indication how my remote connection is doing. There are many states:
* connecting
* connected
* reconnecting
* disconnected
* offline

We want a new state to indicate a slow connection.

Today we have different ways how to convey connection state:

**Connecting**
<img width="192" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/900690/2adc315e-cfb9-450f-82af-316962aca9e4">

**Connected**
<img width="153" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/900690/cd0d79e6-57d6-443e-b650-61a6c543e424">

**Reconnecting**
<img width="420" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/900690/7b1c1459-8aec-4869-9748-e072760bd0c0">

**Disconnected**
<img width="282" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/900690/8db2bf49-769f-43fd-8e00-6419ed9bb17b">

**Offline**
<img width="978" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/900690/fff7dae5-fd5a-49c1-9b4e-e04102e3056c">

The "offline" indicator is actually only being shown when using a web browser and is not specific to remote connections at all.

An idea of how to indicate a slow connection is from the remote indicator as well:

<img width="334" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/900690/a2554d22-7311-4270-ad88-14fb9b623c06">

Though maybe the icon is not best.

**Comment by bpasero** [comment]
Hm an idea I had was to reuse the warning icon and actually indicate the latency to the user:

![image](https://github.com/microsoft/vscode-codicons/assets/900690/596bf579-242b-4ec4-9dec-25ec01ac59d6)

I should probably bring this to a UX call.

**Comment by daviddossett** [comment]
@bpasero you ended up just using `warning`, correct?

**Comment by bpasero** [comment]
Yes I think that is fine.
