### ISSUE TITLE
Share icon

### ISSUE THREAD

**Issue by unthinkmedia** [microsoft/vscode-codicons#185]
**Is your icon request related to a problem? Please describe.**
In VS Code for Education, instructors will be asked to "share" a lesson to students that will be required to complete.

**Describe the solution you'd like**
I would like to have a standard share icon similar to what is used in Fluent

**Additional context**
<img width="513" alt="Screenshot 2023-07-24 at 2 48 15 PM" src="https://github.com/microsoft/vscode-codicons/assets/57981398/7b92448f-9e76-4c8e-a433-eab3d3e10480">

**Comment by hbons** [comment]
Fixed in #214
