### ISSUE TITLE
Icon to run cell and all cells it depends on

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-codicons#190]
**Is your icon request related to a problem? Please describe.**

In notebook, if I want to execute a cell (i.e., cell D) after making a modification to a cell above (i.e., cell A), I have to remember to execute all the cells that D depends on, including cell A, and any other cells in between (i.e., cell C).

In a complex notebook it’s hard to know which cells a modification to one will dirty, which leads to either errors or simply resigning to running all the cells even if it’s unnecessary. When a cell is costly to run, like they can be in ML tasks, this is a major waste of time. 

**Describe the solution you'd like**

We will build a solution to keep track of cell execution dependencies, and would like to add a command to invoke that from any cell. The proposed solution is as listed in this [issue comment](https://github.com/microsoft/vscode-jupyter-internal/issues/441#issuecomment-1664444937). The **icon** and **wording** should both be re-examined.
![image](https://github.com/microsoft/vscode-codicons/assets/10833267/8567bea9-b719-4ee0-9e1f-650f0fa05229)

**Describe alternatives you've considered**

N/A

**Additional context**

Original issue: https://github.com/microsoft/vscode-jupyter-internal/issues/441

cc\ @rebornix

**Comment by hbons** [comment]
I've added this icon some time ago and it lives in the extension: <img width="687" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/103326/0a3ccf30-be54-45b1-98e0-4259f36ff824">

@daviddossett do we need to add this icon to the codicons repo as well?

**Comment by daviddossett** [comment]
Is that command part of the native Notebooks UI? If so, adding to Codicons makes sense. If not, it should probably be only included in the extension.
