### ISSUE TITLE
Mic filled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-codicons#195]
For the voice-to-text support I would like to have a `mic` icon that is filled to indicate recording is in progress.

![275467282-d307644a-3b2f-4c5d-a2b0-d4f59accc5c8](https://github.com/microsoft/vscode-codicons/assets/900690/8a311a66-5dd5-4759-8991-36d688310be2)

**Comment by hbons** [comment]
Has been added to the font by @daviddossett.
