### ISSUE TITLE
VS Code Webview Useing the codicons

### ISSUE THREAD

**Issue by pwmb** [microsoft/vscode-codicons#20]
I am curious, is there a possiblity of exposing of codicons to the vscode extension's webview so that extension developers can use the codicons directly like they use font-awesome (_after adding the dependencies_)?

**Comment by misolori** [comment]
We actually have a [sample webview that uses codicons](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-codicons-sample) from the npm package:

![image](https://user-images.githubusercontent.com/35271042/89581770-6b429200-d7ec-11ea-8905-7f19c6c57aae.png)

There’s an open issue for supporting Codicons natively without the manual reference, see https://github.com/microsoft/vscode/issues/95199.

**Comment by pwmb** [comment]
Yes I knew about the sample webview app, was wondering that natively is there a way.

Thanks for the link to the issue, will follow it to see when it gets added, so that can use it like using css based on theme.
