### ISSUE TITLE
Github "releases" and git version tags would be nice

### ISSUE THREAD

**Issue by darkvertex** [microsoft/vscode-codicons#21]
Love the clean looks of this icon font. Nice work!

I would love to see this repo use Github's "Releases" feature or at least some semantic versioning git tags. I know the version is in the `package.json` but it would be nice to be able to reference a specific release via git tag rather than searching which commit was what version.

**Comment by misolori** [comment]
Thanks for the feedback! I think this is something that we can definitely look into.

**Comment by orta** [comment]
I use [release-it](https://www.npmjs.com/package/release-it) to automate all that stuff

**Comment by misolori** [comment]
Now using release-it (thanks @orta for rec) and I just released on update on the repo and should be reflected now.
