### ISSUE TITLE
Icons to sort alphabetically vs sort by percent

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#210]
**Is your icon request related to a problem? Please describe.**

In the test coverage view, I want to let users toggle whether files are sorted alphabetically or whether they're sorted by the coverage percent.

**Describe the solution you'd like**

Perhaps something along these lines with an alternative version that has `AZ` instead of `%`

https://www.iconfinder.com/icons/5014732/arrow_by_price_data_filter_percent_sort_up_icon

**Describe alternatives you've considered**

There aren't really sorting icons in our existing codicons

**Comment by hbons** [comment]
Since lists in VS Code are usually sorted by alphabet by default, would it be a good idea to only add a "sort percent" button that becomes toggled on press?

**Comment by connor4312** [comment]
Sure 👍

**Comment by hbons** [comment]
Adding `percentage` and `sort-percentage`. Keeping the metaphor simple, just a percent. For this case the context will be obvious.

<img width="198" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/103326/6396555e-1d48-4592-9ccc-5e9669d7556b">
