### ISSUE TITLE
VSCode Stable / Insiders / CodeOSS / Experimental Icons

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-codicons#216]
We added icons to editor labels of the built in editor inputs: [#200147](https://github.com/microsoft/vscode/issues/200147) 

The last editors which need to be adapted are the "Welcome" / "Getting Started" pages which currently set an SVG for the label which is a hack and causes weird behaviour. To fix this and to complete the mentioned task we need the vscode and codeOSS icons as codicons.

**Comment by hbons** [comment]
can you give me a screenshot of what these look like currently?

**Comment by benibenj** [comment]
The Welcome view shows the icon of the product you are currently in.

Insiders:
<img width="207" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/44439583/77cef441-6c8c-4a69-b09e-fc2ea0f80f11">

CodeOSS:
<img width="161" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/44439583/3f452146-f66d-4817-8a67-1da47a53a6f0">

VSCode:
Same as Insiders but blue

Experimental:
Same as Insiders but orange
