### ISSUE TITLE
Icon for left-heavy flame graph view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#23]
In https://github.com/microsoft/vscode-js-profile-visualizer/issues/11 the flame graph now supports a 'left-heavy' view, where callstacks are grouped and sorted by the cumulative time taken, rather than being displayed chronologically. I didn't find a good icon to use for it in our existing codicons.

Speedscope uses a simple arrow, but this is not self-explanitory:

![](https://memes.peet.io/img/20-09-dad28526-bfd2-40c2-a771-3792f405e647.png)

Something like the generic chart icon rotated clockwise 180 degrees would work nicely https://iconmonstr.com/chart-4-svg/

**Comment by misolori** [comment]
We do have this graph icon:

![image](https://user-images.githubusercontent.com/35271042/92640450-25b53100-f292-11ea-831c-0b664989da77.png)

So something like this?

![image](https://user-images.githubusercontent.com/35271042/92640485-34034d00-f292-11ea-9d3c-6c56426c8d6e.png)

**Comment by connor4312** [comment]
Yep, the left version -- since the flame graph is oriented vertically

**Comment by misolori** [comment]
Ahhh, that makes sense now. I can add this in shortly.

**Comment by connor4312** [comment]
Maybe with a small arrow on the left side of the line to indicate the action of 'compacting' the graph? Might be too small to be visible though

**Comment by misolori** [comment]
We could do something like where the arrow is part of the top line? Might be hard to see at smaller sizes though:

![image](https://user-images.githubusercontent.com/35271042/92641433-96a91880-f293-11ea-995e-11619b15e68d.png)

Here's @ 100%

![image](https://user-images.githubusercontent.com/35271042/92641454-9dd02680-f293-11ea-928c-b3d954b30f31.png)

**Comment by connor4312** [comment]
awesome!

**Comment by misolori** [comment]
Fixed via https://github.com/microsoft/vscode-codicons/commit/dd1edb245d2217efcfb931c293b77b78e634e59a. This is now `graph-left` in codicons `0.0.9`.
