### ISSUE TITLE
codicon.html page 404

### ISSUE THREAD

**Issue by wuyiccc** [microsoft/vscode-codicons#231]
**Describe the bug**
Hello, when I click on the link https://microsoft.github.io/vscode-codicons/dist/codicon.html, it shows a 404 error.

**To Reproduce**

**Expected behavior**
Clicking on the link https://microsoft.github.io/vscode-codicons/dist/codicon.html displays the page correctly.

**Screenshots**
<img width="966" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/56572026/da3cac44-547f-4107-9a2d-09ef91b0fec5">

**Environment**
 - OS:  macos edge

**Additional context**

**Comment by Ndeh-007** [comment]
Same Issue. 

Environment
- Browser: Chrome

**Comment by superatomic** [comment]
Looks like this problem was introduced by @hbons here: https://github.com/microsoft/vscode-codicons/commit/20905189385c78c79db022559b7bc6173204e62d

**Comment by connor4312** [comment]
I used this to find codicons while working on the product, eager to see it back...

**Comment by daviddossett** [comment]
@hbons looks like we lost the GH pages site with those changes. Was that intentional?

**Comment by Ghost4Man** [comment]
For anyone looking for a working codicon search:
- https://code.visualstudio.com/api/references/icons-in-labels#icon-listing
- https://icon-sets.iconify.design/codicon/
- https://yesicon.app/codicon

**Comment by hbons** [comment]
Doing some automation and working on getting this back up. Meanwhile you can also download a Release and open dist/codicon.html in your browser.

**Comment by hbons** [comment]
Still some issue wit this.

**Comment by hbons** [comment]
This is back up. Thanks for your patience!
