### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dsmmcken** [microsoft/vscode-codicons#248]
It's been 6 months since the last published npm release. Any chance we could get an updated release? I see there's a release.yml that does the github release, it would good to include the npm release as part of that to reduce friction as much as possible.

**Comment by d13** [comment]
Any update on when this will release? Could really use some of the new icons. 🙏

**Comment by daviddossett** [comment]
Done 
- https://github.com/microsoft/vscode-codicons/releases/tag/0.0.36
- https://www.npmjs.com/package/@vscode/codicons/v/0.0.36
