### ISSUE TITLE
Speaker icon

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-codicons#249]
For text to speech scenarios, an icon would be great, such as this:

<img width="445" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/900690/f31d5166-f949-47fa-a8c0-ba8aadac49fb">

**Comment by daviddossett** [comment]
We have `Codicon.unmute`, which needs an alias, but should work for this case.

![Image](https://github.com/microsoft/vscode-codicons/assets/25163139/5ad08206-1526-4651-b576-285ecacbda21)

**Comment by bpasero** [comment]
![Recording 2024-05-08 at 20 06 32](https://github.com/microsoft/vscode-codicons/assets/900690/89319e80-91bd-4d18-bc5e-184bb6c43e55)

Works great.
