### ISSUE TITLE
Add "Redo" icon

### ISSUE THREAD

**Issue by scotthardwick** [microsoft/vscode-codicons#26]
Hi,
You currently have "discard" that is obviously the Undo button.  However there is not a Redo icon.  Could you please add one?
Thanks

**Comment by misolori** [comment]
This is now in [v0.0.11](https://github.com/microsoft/vscode-codicons/releases/tag/0.0.11)

![image](https://user-images.githubusercontent.com/35271042/94029732-f57d9000-fd71-11ea-85d0-ba9bf1318ee5.png)

**Comment by scotthardwick** [comment]
Thanks!!
