### ISSUE TITLE
Font face url should be variable using SASS

### ISSUE THREAD

**Issue by rjcarneiro** [microsoft/vscode-codicons#27]
Hi,

Due to the fact the generated _css_ has a fixed path to the relative font

```
@font-face {
	font-family: "codicon";
	src: url("./codicon.ttf?2d8845e471b17710e17ce49926ab9dfb") format("truetype");
}
```
This is forcing me to have to put the font file in the same directory as the styling, which makes no sense. If your file structure is something like:

```
wwwroot/
wwwroot/css
wwwroot/fonts
```

Then you need to put `codicon.ttf` in the _css_ folder instead of _fonts_ one.

My suggestion is to create a SASS version where the url if a variable, something like `$vscode-codicons-font-path`.

Thanks.

**Comment by misolori** [comment]
Hey, thanks for checking out our icon font! We actually setup the structure based on how we use it in VS Code. We also have this icon font as a [npm package](https://www.npmjs.com/package/vscode-codicons) if you wanted to import this into a project. You're more than welcome to edit the file/structure if you're copying over the files. Since we don't use SASS I don't see us adding this support any time soon.

**Comment by rjcarneiro** [comment]
Hi @misolori, thank you so much for your message.

The issue I see with your approach is that manual work will be overridden once there's a new package update and maintain that, will be painful...! 

What if I open a pull request and add the SASS support myself? 

I would create a new template similar with `styles.hbs` with a minor changes

```
$vscode-codicons-font-path = {{{ src }}};
@font-face {
	font-family: "{{ fontName }}";
	src: $vscode-codicons-font-path;
}
```

Do you think it's okay or I'm just wasting my time here?

Thanks!

**Comment by misolori** [comment]
I would wait to accept a PR before seeing a demand for this since it feels like a special case and creating a new file means maintaining that one w/ new changes as opposed to a single one.

**Comment by brianignacio5** [comment]
I'm also facing a similar issue.

If trying to use the npm package for vscode extension webview that uses webpack, the relative path will try to resolve the font  path in the entry point directory instead of the actual font directory.

**Comment by rjcarneiro** [comment]
@brianignacio5 it's a pretty disappointing situation because all your files will be all messed up... I believe my suggestion is quite easy and straightforward. 

My workaround is have a PS script that will make sure the files are in the right place, every time we deploy.

**Comment by brianignacio5** [comment]
I've found another fix, using `resolve-url-loader` before `sass-loader` which replace url(###) with proper paths.

**Comment by brianignacio5** [comment]
Sorry, `resolve-url-loader` doesn't fix the issue for all cases. Trying to use vscode-codicons in a webview that is bundle with Webpack and it doesn't load properly since the bundle tries to resolve a vscode-resource://path

**Comment by Profesor08** [comment]
This issue is not related to this package. You have to configure properly your loader and make it to override the font path.

Example for webpack configuration:

To move font file to output `/dist/fonts/codicon.ttf`

> `webpack.config.js`
> ```javascript
>   rules.push({
>     test: /\.(woff|woff2|eot|ttf|otf)$/,
>     use: [
>       {
>         loader: "file-loader",
>         options: {
>           name: "[name].[ext]",
>           outputPath: "fonts/",
>         },
>       },
>     ],
>   });
> ```

> `main.scss`
> ```scss
> @import "../../node_modules/@vscode/codicons/dist/codicon.css";
> ```

**Comment by misolori** [comment]
Thanks @Profesor08 for outlining this, since this is a loader issue I'll go ahead and close this issue.
