### ISSUE TITLE
Request for a double check icon

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-codicons#28]
For my ESLint execution confirmation dialog it would be great to have a double check (two check marks) in the codicon set to indicate that the user has pressed Always Allow.

**Comment by misolori** [comment]
Would something like this work?

![image](https://user-images.githubusercontent.com/35271042/94280979-eb3ecb80-ff02-11ea-862e-8c461af51d49.png)

@ 100%
![image](https://user-images.githubusercontent.com/35271042/94281056-027db900-ff03-11ea-9511-d06f7842f2a7.png)
