### ISSUE TITLE
[New Icon Request] An alternative icon for debug-restart?

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-codicons#29]
Currently we have icon for debug-restart like this: ![image](https://user-images.githubusercontent.com/6193897/97535296-66116f80-19f6-11eb-9763-1713f2b31d77.png)

This icon looks good, but when it comes together with the refresh button, Users might feel a little bit confused:

![image](https://user-images.githubusercontent.com/6193897/97535484-a8d34780-19f6-11eb-996f-e5afd36a8534.png)

Can we provide a new alternative icon for debug-restart, something like: (sorry for my weak PS skill 😄 )

![image](https://user-images.githubusercontent.com/6193897/97536001-737b2980-19f7-11eb-8d1f-c6fe2aa82f47.png)

Other IDEs has similar pattern:
- IntelliJ ![image](https://user-images.githubusercontent.com/6193897/97536624-67dc3280-19f8-11eb-805c-642fd2737ab8.png)

- Eclipse ![image](https://user-images.githubusercontent.com/6193897/97536723-8fcb9600-19f8-11eb-894e-5cd6a9d4a9b4.png)

**Comment by misolori** [comment]
Hmm...not sure how I feel about introducing yet another variant for the same icon. Are you able to place the relaunch icon somewhere else where it doesn't clash with refresh? This is the firs time I've seen an extension use both so I'd like to see a bigger need for it before we consider it.

**Comment by jdneo** [comment]
Thanks for the suggestion, I'll see how I can tune the appearance. 

BTW, the current relaunch icon looks great in the debug toolbar. I can quickly get it's meaning by the first glance
![image](https://user-images.githubusercontent.com/6193897/99634726-f08c4280-2a7b-11eb-9c2b-d8309cb8691a.png)

If use this icon independently somewhere else outside the debug toolbar, it's a little bit difficult for me to distinguish it from refresh. It's just my personal opinion. 😃

**Comment by misolori** [comment]
I've added a new icon, `debug-rerun`, that should meet this request:

![image](https://user-images.githubusercontent.com/35271042/108765873-3a684700-7509-11eb-8bf4-63ed1b58b111.png)

cc @connor4312

**Comment by jdneo** [comment]
Thank you @misolori!
