### ISSUE TITLE
circle-large-filled has incorrect width

### ISSUE THREAD

**Issue by cyberalien** [microsoft/vscode-codicons#31]
Icon circle-large-filled is 17x16 instead of 16x16 with 1 extra pixel on left side.

**Comment by misolori** [comment]
Hey thanks for catching this. Not sure why it's exporting at 17px when I've set everything correctly:

![image](https://user-images.githubusercontent.com/35271042/100264041-1fcf0380-2f03-11eb-8123-36e16659cf72.png)

I'll file a bug to Figma.
