### ISSUE TITLE
Icons for TestRunStates

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#34]
Tests in the new API have several states:

```
export enum TestRunState {
	// Initial state
	Unset = 0,
	// Test is currently running
	Running = 1,
	// Test run has passed
	Passed = 2,
	// Test run has failed (on an assertion)
	Failed = 3,
	// Test run has been skipped
	Skipped = 4,
	// Test run failed for some other reason (compilation error, timeout, etc)
	Errored = 5
}
```

I would like icons to represent these in the sidebars 🙂  Some existing icons might work, e.g.

- Unset: no icon, or maybe some "dimmed" icon like an unset breakpoint?
- Running: `refresh`
- Passed: `check`
- Failed: `close`
- Skipped: same as unset? Not sure... This would be if you have something like `test.only` in your code.
- Errored: `issues`

This is being implemented in core so I can have different colors/opacities/etc in the icons. Let me know what you think.

**Comment by connor4312** [comment]
I also want to add an additional state -- Queued

**Comment by misolori** [comment]
Would something like this work:

![image](https://user-images.githubusercontent.com/35271042/101965020-2084bc80-3bc8-11eb-9e9f-48766f378d5e.png)

**Comment by connor4312** [comment]
Yea, that looks pretty 🙂 I'm not sure about the queued one though... maybe a small yellow clock symbol?

**Comment by misolori** [comment]
Yea we can try that too:

![image](https://user-images.githubusercontent.com/35271042/102047409-11ea0100-3d92-11eb-9d95-378eaca318a4.png)

**Comment by connor4312** [comment]
That's beautiful 😍

**Comment by connor4312** [comment]
I wonder what you think about animation on the "running" icon. It's never felt very clear to me. At the moment we don't really that icon heavily or at all in core. Maybe now that it's getting a prominent display--which could show for several seconds on slow cases--we could make it CSS-based with a smooth growing/shinking effect on the balls, instead of a plain spinning effect.

**Comment by misolori** [comment]
The loading icon is now updated in master and [should follow this pattern](https://github.com/microsoft/vscode/issues/112593#issuecomment-745506773).
