### ISSUE TITLE
Confused as to how to use the library

### ISSUE THREAD

**Issue by IliaSmagloy** [microsoft/vscode-codicons#36]
Hello! 

I'm working on my extension currently, using your library.
I'm mostly guided by [this example](https://github.com/microsoft/vscode-extension-samples/blob/master/webview-codicons-sample/src/extension.ts), and your read me and unfortunately it doesn't seem to work.

I've tried installing the library and calling plane `<div class='codicon codicon-add'> add</div>` 
Which doesn't seem to work for me.

I've also tried importing using the URI-s your css and font like shown in the example, this didn't work as well. Am I missing something in the documentation? Besides installing the library, what are the needed steps in order to use the icons in my webview?

Thanks a lot!

**Comment by misolori** [comment]
@IliaSmagloy have you tried downloading the [extension sample](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-codicons-sample) and building that first to make sure the extension is building correctly? Make sure you run `npm install` on the repo as that will install the [vscode-codicons](https://www.npmjs.com/package/vscode-codicons) module. The docs reference how to build this with the VS Code source code, which is different than building with an extension.

**Comment by misolori** [comment]
Let me know if that doesn't answer your question.
