### ISSUE TITLE
[New Icon Request] Icons for type hierarchy

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-codicons#37]
I'm developing type hierarchy feature for Java users in VS Code and find there is no type hierarchy existing in VS Code. I'm going to contribute to the reference view by [References Viewlet API](https://code.visualstudio.com/updates/v1_50#_references-viewlet-api), the type hierarchy icons will show in the reference view as the following screenshot shows:
![image](https://user-images.githubusercontent.com/45906942/104559286-2108eb00-567f-11eb-9d4f-466ea64dce93.png)

Usually, there are three views in type hierarchy, they are `Type Hierarchy`, `SuperType Hierarchy` and `SubType hierarchy`. `SuperType Hierarchy` shows the super types of the given type while the `SubType hierarchy` shows the sub types of the given type. `Type Hierarchy` shows both of them.

It could be very great and intuitional if there are meaningful view icons in the type hierarchy view. 

Other IDEs' icons (in red square):

- IntelliJ  
![hierarchyIDEA](https://user-images.githubusercontent.com/45906942/104558456-c91db480-567d-11eb-93d5-9bd6447fb0cb.jpg)

- Eclipse
![hierarchyEclipse](https://user-images.githubusercontent.com/45906942/104558570-fb2f1680-567d-11eb-870c-3d3f8bfae355.jpg)

**Comment by misolori** [comment]
I'm not sure how useful these icons would apply to other areas, we try to avoid adding extension-specific icons and go with more of a utilitarian approach.

@jrieken do you know if any of these icons would be useful in other languages?

**Comment by jrieken** [comment]
Yeah, generally it might be useful. There is a request for VS Code supporting a type hierarchy from different languages. We don't offer this feature (yet) in VS Code but offer a way to customise/drive the references view to implement this by extensions themselves. If we eventually have a built-in type hierarchy view we would need icons anyways, so having them already now isn't bad

**Comment by CsCherrYY** [comment]
@misolori  @jrieken
Thanks a lot! It will be especially useful for many languages if we have the type hierarchy icons.

**Comment by misolori** [comment]
Alright, since we don't have anything close to this in the Microsoft Design Language (MDL) icon library, which is where most of our icons come from, I'll send a request to get these worked on and will point to the examples. Will update the issue when we have some comps.

**Comment by misolori** [comment]
Here's the first version of these, let me know what you think:

![image](https://user-images.githubusercontent.com/35271042/106647837-500ad200-6544-11eb-8d8c-bf3ef2108415.png)

- `type-hierarchy-sub`
- `type-hierarchy-super`
- `type-hierarchy`

**Comment by CsCherrYY** [comment]
> Here's the first version of these, let me know what you think:
> 
> ![image](https://user-images.githubusercontent.com/35271042/106647837-500ad200-6544-11eb-8d8c-bf3ef2108415.png)
> 
> * `type-hierarchy-sub`
> * `type-hierarchy-super`
> * `type-hierarchy`

Looks fairly good. When will them be available for extensions?

**Comment by misolori** [comment]
This will be in the next Insiders after v1.53 ships later this week. Will update the issue here when it's available.

**Comment by akaroml** [comment]
The icons look perfect. Thank you @misolori

**Comment by CsCherrYY** [comment]
Thank you @misolori !
![Screenshot](https://user-images.githubusercontent.com/45906942/109474034-0794f480-7aaf-11eb-90e5-7bbf7e083091.jpg)
