### ISSUE TITLE
Question regarding codicons license use in personal project

### ISSUE THREAD

**Issue by eddyw** [microsoft/vscode-codicons#38]
Hi 👋 

From the `README.md`:
>Microsoft and any contributors grant you a license to the Microsoft documentation and **other content in this repository** under the Creative Commons Attribution 4.0 International Public License, see the LICENSE file, and grant you a license to **any code in the repository under the MIT License**, see the LICENSE-CODE file.

Could someone clarify what "other content in this repository" means or refers to? 😅 

I want to use codicons in a personal website (some symbols) but I'm confused about the license. With "any code" also refer to the `svg` files under `src`? And if so, does it mean SVGs are licensed under MIT .. but docs under CC4? 🤔 

I guess a more direct question would be if I can use certain SVG codicons' icons in a personal website and if so, do I need to provide the copy of the `LICENSE-CODE` only in the code or dir where codicons are in my project (MIT) or also CC4 attribution? 🤔 

If CC4 attribution is required, is it okay to embed it in the SVG icon as a comment? (Sort of like FontAwesome does)

**Comment by misolori** [comment]
👋 Hey, thanks for your interest in wanting to use codicons elsewhere. The "other content..." is a catch all for everything in this repo, so it means that "everything else" 😄 . You can definitely use the SVG icons or the icon font as long as you place an attribution to it (that's the [CC4 attribution](https://creativecommons.org/licenses/by/4.0/legalcode)).

It's probably easier to just use the icon font, you can use the [npm package](https://www.npmjs.com/package/vscode-codicons) if you're using node dependencies.

Let me know if that answers your questions 😄

**Comment by misolori** [comment]
Let me know of that doesn't answer your question, will be closing this issue.

**Comment by eddyw** [comment]
Thanks for clarifying! Yes, that answers my question 👍
