### ISSUE TITLE
include list bullet styles

### ISSUE THREAD

**Issue by indrora** [microsoft/vscode-codicons#4]
With a lot of icon fonts (Font Awesome, for example) you can use

```html
<ul>
  <li class="fa fa-icon-bell">List Item</li>
  <li class="fa fa-icon-star">List Item</li>
</ul>
```

and the marker for that bullet point is changed to that icon in the font. 

Currently, doing `<li class="codicon codicon-symbol-member">womp</li>` causes the list item to break in new and exciting ways, depending on the browser that you use.

**Comment by daviddossett** [comment]
Given that this isn't something we would use in VS Code, I think it's unlikely that we'll tackle this. If there's a case to be made for it's use in the core product, I'm happy to reopen and take a look.
