### ISSUE TITLE
[New Icon Request] Notebook Template

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-codicons#40]
Looks like the general pattern for "template" icons has a dotted line rectangle behind the image. 
Could we get an icon that looks like this but with a notebook in front for notebook templates? 
![image](https://user-images.githubusercontent.com/19276747/107164054-f5b5ab00-6961-11eb-8838-531ce3e91537.png)
![image](https://user-images.githubusercontent.com/19276747/107164068-08c87b00-6962-11eb-80f1-5fcd85017e7b.png)

**Comment by misolori** [comment]
![image](https://user-images.githubusercontent.com/35271042/108261050-ed0a6500-7117-11eb-9574-35ac03643b08.png)
