### ISSUE TITLE
Versions is a bit heavy

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#41]
Here is out current version

![image](https://user-images.githubusercontent.com/641685/107326034-c5acfb80-6a78-11eb-9142-fd9865440d0b.png)

Here is the octicons version

![image](https://user-images.githubusercontent.com/641685/107326111-e83f1480-6a78-11eb-81bf-6b9a267cb149.png)

I would love to see our version much closer to the octicon version.

**Comment by misolori** [comment]
For some reason that first one was thicker than the rest, fixed:

![image](https://user-images.githubusercontent.com/35271042/108261129-04e1e900-7118-11eb-86b7-f1c5592a431d.png)
