### ISSUE TITLE
Icon for 'auto rerun' tests

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#42]
For tests I'd like an icon to use in the menu bar for the "auto rerun" state. Maybe something like this?

![2021_02_10 15_30 Office Lens](https://user-images.githubusercontent.com/2230985/107586519-f09c6a00-6bb4-11eb-9a57-6c9e7dfa81a6.jpg)

JetBrainz has this: https://www.jetbrains.com/help/webstorm/rerunning-tests.html#auto

**Comment by misolori** [comment]
Would this be a similar request to https://github.com/microsoft/vscode-codicons/issues/29?

**Comment by connor4312** [comment]
yea, it could be

**Comment by misolori** [comment]
Closing as duplicate
