### ISSUE TITLE
[New Icon Request] New Notebook

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-codicons#43]
![image](https://user-images.githubusercontent.com/19276747/107683587-96ec7c00-6c56-11eb-8828-21b04b25c612.png)

**Comment by misolori** [comment]
Hmm...this is something we're trying to avoid with our icons is the notion of "new" for all things because it is a slippery slope and you can have a lot of "new" icons. Would the `+` icon not work?

**Comment by claudiaregio** [comment]
Ah I see... this would be used for the notebook panel where the top two icons would lead to "create new notebook" and create new notebook from template". For design consistency I figured it would make the most sense to have those two like icons next to each other. Do you still recommend the + icon?

**Comment by misolori** [comment]
You can try using a single `+` and open a quick pick with the two options. It's an extra step but it does reduce the amount of visual noise in the UI. You also want to make sure that icons are only used for the most used actions and then place others in an ellipsis `...`. Here's how other extensions use the `+` in different views:

![image](https://user-images.githubusercontent.com/35271042/107711504-9f57ad80-6c7c-11eb-8b53-8f9dfe1db667.png)


![image](https://user-images.githubusercontent.com/35271042/107711498-9c5cbd00-6c7c-11eb-8d22-0698523f5f55.png)


Also, soon enough I believe we'll be enabling dropdowns on actions so you can have both appear from the single icon.

**Comment by claudiaregio** [comment]
That would be awesome to have drop downs on the actions!!! *happy dance*

**Comment by misolori** [comment]
I'll close this issue then since we don't want to add any additional `new` icons. Thanks!
