### ISSUE TITLE
Discrepancies between repo and official product icon reference

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/vscode-codicons#44]
I'm not sure if this a documentation problem, a real bug or something I misunderstand, but here we go.

When I compare the list of icons in this repository, which is apparently what is used by vscode, I would expect that it corresponds to the [product icon reference](https://code.visualstudio.com/api/references/icons-in-labels#icon-listing), which however is not the case. Fore example I don't see any of the `find-*` icons mentioned in the reference.

And here's a side question, but also related: does the monaco-editor use exactly the same icons or just a subset? For example, I get no output for `codicon-output`, even though this icon is both, in this repo and mentioned in the icon reference.

**Comment by misolori** [comment]
So the list on the product icon reference page has a "codicon id" column, this is the id that is used in this repo:

![image](https://user-images.githubusercontent.com/35271042/108110256-ddbbe680-7047-11eb-9b38-cf8bd0459801.png)

So the `find-*` icons, the second column is the id:

![image](https://user-images.githubusercontent.com/35271042/108110381-07750d80-7048-11eb-9408-c1fe8b5b57cc.png)

Does that help? And for the monaco editor, they are using the same icons however I'm not sure how often the editor gets updated with the latest.

**Comment by mike-lischke** [comment]
OK, thanks, that explains the name differences. But the other question still stands: does monaco-editor use the same set of codicons? If so, why is nothing shown for the `output` codicon? Looking the HTML code I see it doesn't add the `::before` pseudo node for that, which it does for other codicons.

Since monaco-editor is created from vscode code, I hoope this is a valid question here.

**Comment by misolori** [comment]
Yes, codicons are part of the monaco editor since you see them in the suggest widget. You might want to post in https://github.com/Microsoft/monaco-editor and cc me about it there and show an example of how you're referencing the icons.

**Comment by misolori** [comment]
Will close this issue as I believe your question was answered, please free to create a new issue here or in the monaco-editor repo for any new questions/issues. Thanks!
