### ISSUE TITLE
[New Icon Request] Run all above/below

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-codicons#45]
![image](https://user-images.githubusercontent.com/19276747/108132977-a6a9fd00-7068-11eb-8bae-0c93e16ce013.png)
![image](https://user-images.githubusercontent.com/19276747/108132987-add10b00-7068-11eb-9cb4-ff2cafa28f86.png)

**Comment by misolori** [comment]
![image](https://user-images.githubusercontent.com/35271042/108260997-db28c200-7117-11eb-9cd5-26a41527ef51.png)

![image](https://user-images.githubusercontent.com/35271042/108261013-debc4900-7117-11eb-8f7e-2df870843141.png)
