### ISSUE TITLE
`folder-opened.svg` icon is broken when multiple are included the same page

### ISSUE THREAD

**Issue by feross** [microsoft/vscode-codicons#48]
Because the `folder-opened.svg` icon uses `clip-path` with an `id` reference, the icon will break if more than one are included in the page at the same time. 

```
<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" fill="currentColor"><g clip-path="url(#clip0)"><path d="M.5 14h12l.48-.37 2.63-7-.48-.63H13V3.5l-.5-.5H6.71l-.86-.85L5.5 2h-5l-.5.5v11l.5.5zM1 3h4.29l.86.85.35.15H12v2H8.5l-.35.15-.86.85H2.5l-.47.34-1 3.08L1 3zm11.13 10H1.19l1.67-5H7.5l.35-.15.86-.85h5.79l-2.37 6z"/></g><defs><clipPath id="clip0"><path d="M0 0h16v16H0V0z"/></clipPath></defs></svg>
```

Is there any way to remove this or stop using an id? The `id` attribute which shouldn't be used in a page more than once so perhaps the second icon is using the first's `clip-path`?

See this related issue: https://github.com/chakra-ui/chakra-ui/issues/3442

**Comment by misolori** [comment]
Is there a reason why you aren't using the icon font w/ the css? This repo is focused on the icon font.

**Comment by misolori** [comment]
Also, not sure where you are getting that svg icon from, but [this is the one](https://github.com/microsoft/vscode-codicons/blob/main/src/icons/folder-opened.svg) from this repo that doesn't use any clip-paths:

```svg
<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" fill="currentColor"><path d="M1.5 14h11l.48-.37 2.63-7-.48-.63H14V3.5l-.5-.5H7.71l-.86-.85L6.5 2h-5l-.5.5v11l.5.5zM2 3h4.29l.86.85.35.15H13v2H8.5l-.35.15-.86.85H3.5l-.47.34-1 3.08L2 3zm10.13 10H2.19l1.67-5H7.5l.35-.15.86-.85h5.79l-2.37 6z"/></svg>
```
