### ISSUE TITLE
Request to speak with Microsoft package maintainer regarding licensing for this package

### ISSUE THREAD

**Issue by kenzieschmoll** [microsoft/vscode-codicons#49]
Hello,

I published [package:codicon](https://pub.dev/packages/codicon), which is a Dart wrapper around the codicon.ttf file found in this package. The LICENSE for package:codicon contains both the MIT license and the CC-BY 4.0 license (both taken from this repository) and linked from in this repository's [README](https://github.com/microsoft/vscode-codicons#legal-notices). 

However, it appears that the information in the readme at https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons link to a different Creative Commons license (Creative Commons - ShareAlike (CC BY-SA)). Which is correct? Is our package (package:codicon) correctly licensed under the same terms that this repository is (MIT and CC BY 4.0), or should both this repository and package:codicon be licensed under MIT and CC BY-SA?

Happy to follow up offline if that is easier - thanks for your help.

**Comment by misolori** [comment]
Hello, the codicon file that's in this repo is actually bundled inside of the [vscode repo here](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/codicons/codicon/codicon.ttf). The extension that you linked to is a separate third party file icon theme that is not related to codicons. The [license](https://github.com/microsoft/vscode-codicons/blob/main/LICENSE) in this repo is the correct one. Hope that answers your quetsion!
