### ISSUE TITLE
git-branch icon missing

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-codicons#5]
![image](https://user-images.githubusercontent.com/530988/73981934-3b90fb00-492b-11ea-8c68-7af0f98f2407.png)

This seems to be missing, right? Any other place where I can find it?

**Comment by misolori** [comment]
This should be the same as `source-control`. Does that work for you?

**Comment by letmaik** [comment]
Ah thanks, that's it! I should have looked at that to figure out the aliases: https://github.com/microsoft/vscode-codicons/blob/f0caa623812a8ed5059516277675b4158d4c4867/src/template/mapping.json#L32-L35
