### ISSUE TITLE
Save As Template

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-codicons#50]
For the notebook templates feature we need to be able to differentiate between save notebook and save as template. 
Could we get an icon like this to indicate "Save as Template"? 
![image](https://user-images.githubusercontent.com/19276747/112386566-5ac52600-8cae-11eb-999c-baf11e33c3bc.png)

**Comment by misolori** [comment]
Hmm...this one is tricky because we don't want to introduce a pattern where there are variances of "Save". Could use the save icon and then show a dropdown for both save? I'd like to avoid creating these specific variances.
