### ISSUE TITLE
Icons for terminal tabs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-codicons#51]
As discussed, to support https://github.com/microsoft/vscode/issues/10546, https://github.com/microsoft/vscode/issues/120241 I'd like to request the following icons:

- Command Prompt: existing `terminal` icon with `C:\` or `C:` in it?
- PowerShell: slanted icon matching our style containing `>_`
- Tmux: [ref](https://github.com/tmux/tmux/wiki), note the slightly heavier bottom line
- Debian: [ref](https://www.debian.org/)
- Ubuntu: The "circle of friends", waiting on assets for this
- Linux: penguin icon, this will be used as a fallback for WSL terminals

**Comment by misolori** [comment]
Here are the updated icons for each these (Ubuntu pending the artwork we get):

![image](https://user-images.githubusercontent.com/35271042/113751162-783bbc00-96c0-11eb-93c9-f10fae50f6ed.png)
