### ISSUE TITLE
Run by Line

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-codicons#52]
Jupyter extension would like to add the run by line icon to the cell toolbar and would like to match the theme of the other vs codicons in the cell toolbar (keep it snazzy) 

This is the icon currently used for run by line in our stable webview implementation. 
![image](https://user-images.githubusercontent.com/19276747/114652293-706cb080-9c9a-11eb-95f6-da5e3a47b33e.png)

**Comment by misolori** [comment]
<img width="131" alt="CleanShot 2021-04-21 at 13 54 24" src="https://user-images.githubusercontent.com/35271042/115619736-1e82e680-a2a9-11eb-8eb9-83f42285bc3d.png">
