### ISSUE TITLE
Add a filled filter icon

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#53]
It would be great to be able to differentiate when a filter is active or not.

Would be nice for the Problems view and I would also like it for usages in GitLens.

**Comment by misolori** [comment]
<img width="250" alt="CleanShot 2021-04-21 at 13 03 34" src="https://user-images.githubusercontent.com/35271042/115614039-0360a880-a2a2-11eb-9902-b90c96183f18.png">
