### ISSUE TITLE
Add an "add person" icon

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#54]
Something like this:

![image](https://user-images.githubusercontent.com/641685/114969260-08f36400-9e46-11eb-9063-628689058dec.png)

I would like to use it in GitLens for adding co-authors. The above is the icon I am currently using, but the plus should probably be an overlay in the bottom right like our other + icons.

**Comment by misolori** [comment]
<img width="130" alt="CleanShot 2021-04-21 at 12 35 13" src="https://user-images.githubusercontent.com/35271042/115610657-06599a00-a29e-11eb-8d8c-5450ead389ad.png">
