### ISSUE TITLE
Add an uncolored version of our disconnect icon

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#55]
While we have a good disconnect icon, because it is used for debugging it has a color, and I would like to have a normal version to use. I currently am using a copied SVG version in GitLens today.

**Comment by misolori** [comment]
We don't add specific icons that don't have colors so i think this would need to be done on the VS Code side to scope colors for certain views. in this case only have colors in the debug view + toolbar. Can you create an issue there?
