### ISSUE TITLE
Add a copy icon

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#56]
We currently only have a clipboard icon, but imo it isn't too friendly for copy operations

Here is the one I am currently using in GitLens:
![image](https://user-images.githubusercontent.com/641685/114969702-f299d800-9e46-11eb-8b93-40c8e57342ef.png)

An alternate version with a globe or "link" overlay would be nice as well.

![image](https://user-images.githubusercontent.com/641685/114970374-51138600-9e48-11eb-894a-4f886d247842.png)

**Comment by misolori** [comment]
<img width="118" alt="CleanShot 2021-04-21 at 12 29 25" src="https://user-images.githubusercontent.com/35271042/115610111-44a28980-a29d-11eb-92da-56b612c77bce.png">
