### ISSUE TITLE
Add a "swap" icon

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#57]
Here is the icon I am currently using to swap comparisons in GitLens:

![image](https://user-images.githubusercontent.com/641685/114970224-02fe8280-9e48-11eb-9fce-9aaa700a087d.png)

**Comment by misolori** [comment]
<img width="123" alt="CleanShot 2021-04-21 at 11 03 43" src="https://user-images.githubusercontent.com/35271042/115600181-41090580-a291-11eb-96c4-3dbca5fb3454.png">
