### ISSUE TITLE
Add a "no" check icon

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#58]
Something similar to this -- for when a check-able operation isn't support

![image](https://user-images.githubusercontent.com/641685/114970291-2a554f80-9e48-11eb-8890-417b1cf854df.png)

**Comment by misolori** [comment]
What's the context for this? Can we just use the circle/slash instead? I'm generally not a fan of adding modifiers on checkmarks as it makes it harder to understand at a quick glance
