### ISSUE TITLE
Considering add 'run-all' button into codicons?

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-codicons#6]
https://github.com/microsoft/vscode-icons/blob/master/icons/dark/run-all.svg

**Comment by misolori** [comment]
We can certainly add this to the `codicons` font icon, surprised it's not in there already. I'll make sure and that shortly.

**Comment by jdneo** [comment]
Thank you @misolori, does that mean I can reference this icon in next VS Code release?

**Comment by misolori** [comment]
Yes, it’ll also be available in tomorrow’s Insiders.
