### ISSUE TITLE
Smart Select Icon

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-codicons#60]
Smart Select is a feature that uses the dependency graph between cells to "magically" select them for you. 
Icon we were using in spec is this magic wand type of icon. 

Could we get this or something very similar for the feature to add to cell toolbar? 
![image](https://user-images.githubusercontent.com/19276747/115074588-c154f280-9eae-11eb-8be0-ab62b3365e2d.png)

**Comment by misolori** [comment]
<img width="140" alt="CleanShot 2021-04-21 at 13 42 13" src="https://user-images.githubusercontent.com/35271042/115618333-64d74600-a2a7-11eb-891f-84e27ac7c5ed.png">
