### ISSUE TITLE
Add terminal-ubuntu icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-codicons#61]
Follow up from https://github.com/microsoft/vscode-codicons/issues/51, we have the assets for it now.

**Comment by misolori** [comment]
Added `terminal-ubuntu`:

<img width="256" alt="CleanShot 2021-04-20 at 09 46 09" src="https://user-images.githubusercontent.com/35271042/115434377-7a704100-a1bd-11eb-9460-2ebf8c857c5c.png">
