### ISSUE TITLE
Refresh icon overlapping shape artifact 

### ISSUE THREAD

**Issue by dsmmcken** [microsoft/vscode-codicons#62]
The refresh icon has overlapping paths that cause an artifact in the generated output. 🦅 👀 

Suggested fix: manually merge your paths into one shape. 

As shown in vscode:
![image](https://user-images.githubusercontent.com/1576283/117059341-b3480400-aced-11eb-90b3-dd428efece66.png)

As shown individually: 
![image](https://user-images.githubusercontent.com/1576283/117059501-decaee80-aced-11eb-9e1d-4d52a2d29058.png)

**Comment by misolori** [comment]
Great find! I'll see if I can tweak the paths here as this appears to happen when the font gets loaded.

**Comment by misolori** [comment]
🥳  No more ugly refresh icon

![image](https://user-images.githubusercontent.com/35271042/117208262-c7e9d200-ada9-11eb-9037-03f670da9af9.png)
