### ISSUE TITLE
Inspect icon request

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#65]
See context in internal backlog issue 2056. We'd like an inspect-like icon:

![image](https://user-images.githubusercontent.com/2230985/117497527-75392300-af2d-11eb-88d1-8c5b1f6bf4e5.png)

**Comment by misolori** [comment]
![image](https://user-images.githubusercontent.com/35271042/117500842-0f02cf00-af32-11eb-80d3-3775477e3108.png)

**Comment by connor4312** [comment]
That was fast! 🚀
