### ISSUE TITLE
New GH icon request

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-codicons#67]
GH just came out with some new icons, we should update ours and add the new ones https://github.blog/changelog/2021-06-08-new-issue-and-pull-request-state-icons/

**Comment by misolori** [comment]
I think if we are missing some we can add but I don't think we need to update existing ones as we've created our own style with codicons. Are there any specific icons you are thinking about?

**Comment by Tyriar** [comment]
We should align with their icons as they're the new way they show up in github. Otherwise users need to know 2 different symbols for open and closed issues for example?

**Comment by misolori** [comment]
Updated the following icons:
- `issue-closed` now points to `pass`
- `issue-draft`
- `git-pull-request-closed`
- `git-pull-request-draft`

<img width="742" alt="CleanShot 2021-07-07 at 11 19 58@2x" src="https://user-images.githubusercontent.com/35271042/124809720-48958d80-df15-11eb-9a1c-e089caf3a28e.png">

<img width="628" alt="CleanShot 2021-07-07 at 11 20 09@2x" src="https://user-images.githubusercontent.com/35271042/124809743-4fbc9b80-df15-11eb-90fc-527d5969a6fa.png">

**Comment by Tyriar** [comment]
FYI @alexr00
