### ISSUE TITLE
Considering add a new icon to represent library(dependency)

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-codicons#7]
Our extension contains a explorer to show the user's project dependencies. (the node `Maven Dependencies` in the below picture)
<img width="369" alt="Screen Shot 2020-03-13 at 5 55 45 PM" src="https://user-images.githubusercontent.com/6193897/76611045-d39a8980-6554-11ea-968f-b022e4bf711f.png">

Currently we are using `files` to represent it. Is it possible to add a new icon to represent library?

**Comment by misolori** [comment]
We have `book`, would this work for you?

![image](https://user-images.githubusercontent.com/35271042/76782812-15eae300-676e-11ea-85ec-7015951d347d.png)

**Comment by jdneo** [comment]
Thank you @misolori.

Yes, book is something we hope to use. But the only problem for it is: it's not expressing the meaning of multiple.

Here is some examples in other IDE:

IntelliJ:
<img width="475" alt="Screen Shot 2020-03-17 at 9 41 02 AM" src="https://user-images.githubusercontent.com/6193897/76813850-2e253580-6834-11ea-91fa-9b99a03cb4cb.png">

Eclipse:
<img width="354" alt="Screen Shot 2020-03-17 at 9 43 12 AM" src="https://user-images.githubusercontent.com/6193897/76813854-33828000-6834-11ea-9735-e5013e76669a.png">

The icon is more like `books` or `library`.

**Comment by misolori** [comment]
Sorry for delay, we also have this `library` icon from the MDL icons, would this work?

![image](https://user-images.githubusercontent.com/35271042/77444562-3daefc00-6da9-11ea-9948-56b8f4bae01e.png)

**Comment by misolori** [comment]
Added `library`:

![image](https://user-images.githubusercontent.com/35271042/77477796-20deec80-6dda-11ea-910c-3b396545fd25.png)

**Comment by jdneo** [comment]
Thanks @misolori, this looks good to me!
