### ISSUE TITLE
Icon request for Azure / Azure Repos

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#70]
We will need a good icon to use for Azure repos in the Remote Repositories extension. It should probably just be a generic Azure icon (since I'm using the GitHub icon for GitHub repos).

**Comment by misolori** [comment]
Added `azure`

<img width="149" alt="CleanShot 2021-07-06 at 14 53 20@2x" src="https://user-images.githubusercontent.com/35271042/124671153-ed5a9100-de69-11eb-88bd-7dd3fa80a6cb.png">
