### ISSUE TITLE
New icon to distinguish normal commits from indexed commits (e.g. commits with rich navigation support)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-codicons#71]
Again for the Remote Repositories extension we need an icon to use to convey the difference between a normal commit and an indexed commit.

**Comment by misolori** [comment]
Added the following icons:
- `layers`
- `layers-dot`
- `layers-active`
- `compass`
- `compass-dot`
- `compass-active`
<img width="386" alt="CleanShot 2021-07-06 at 14 52 22@2x" src="https://user-images.githubusercontent.com/35271042/124671068-c7cd8780-de69-11eb-8e1f-a3d350d301c8.png">

<img width="414" alt="CleanShot 2021-07-06 at 14 52 30@2x" src="https://user-images.githubusercontent.com/35271042/124671081-cc923b80-de69-11eb-871c-99caa492cf59.png">

**Comment by dbaeumer** [comment]
I integrated the new icons.
