### ISSUE TITLE
Request for a "run with coverage" icon

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#73]
This should be similar to the `debug-alt` icon, but instead of a bug have some other representation of coverage. Jetbrainz uses a shield, I've also seen just an abstract checkboard pattern used before. No specific requirements, just a different icon 🙂

**Comment by misolori** [comment]
Here's a couple of options, let me know which one works best or i can also try a few alternates as well:

<img width="387" alt="CleanShot 2021-07-14 at 11 50 31@2x" src="https://user-images.githubusercontent.com/35271042/125676527-a39d3d40-6368-4855-ae95-638eee143aec.png">

**Comment by connor4312** [comment]
Hm, maybe the layers one?

Could also try a paintbrush, since (a) we'll paint your code in nice colors indicating what's covered and not, and (b) paint coverage is a thing. Maybe that's too obscure, this is a hard one 😛

**Comment by misolori** [comment]
Here's a few more:

<img width="470" alt="CleanShot 2021-07-14 at 14 33 58@2x" src="https://user-images.githubusercontent.com/35271042/125696063-af61778d-52f0-475a-b29e-27e6c7b03047.png">

I still don't feel like any of these are representing the action the best. Which makes me wonder how well users will understand this icon? Is it worth to take a step back and see if the actions can be added to some type of context menu that doesn't require icons? We don't want to get into a rabbit hole of creating several other icons for "run with {fill in the blank}"?

**Comment by connor4312** [comment]
I think the lightbulb works nice. I think a menubar icon would be useful here for discoverability -- I don't anticipate having any more run "modes", and if so those could definitely go in an overflow menu.

**Comment by misolori** [comment]
<img width="158" alt="CleanShot 2021-07-15 at 16 20 44@2x" src="https://user-images.githubusercontent.com/35271042/125869682-92d920f9-705c-4e01-b121-856103449e96.png">
