### ISSUE TITLE
React Icon

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode-codicons#74]
As far as I understand, there is no way to include this icon into suggestions / views, but React is a very popular library and there is a lot of extensions for that. It is good to have this icon (to indicate JSX components in suggestions for example).

But, React icon in a solid white color isn't very distinguishable. Can we somehow make it blue labels e.g. `$(react) Component` → 
![image](https://user-images.githubusercontent.com/46503702/126084441-924abbeb-a205-4bfc-af28-e4f3f73528c3.png)

to emphasize the icon itself?

**Comment by misolori** [comment]
React is a language and I don't think we want to confused product icons with language icons as this would open the door for all other language icon requests. So unfortunately I'm going to say that this is out of scope.
