### ISSUE TITLE
Add Docker and Kubernetes icons to codicon suite

### ISSUE THREAD

**Issue by bprabhus** [microsoft/vscode-codicons#75]
I'm using VSCode extension Activitus bar that shows Activity bar at the bottom. It relies on the Codicon suite to provide activity views. **I would love to see Docker Icons be part of the codicon suite.**

![Screenshot](https://raw.githubusercontent.com/bprabhus/bucket/master/vscode/activitus_docker.png)
Extension - Activitus bar : [Link](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar)

**Comment by misolori** [comment]
Logos depends on the license agreements for each product. I know that Docker does not want us to add their logos (from previous internal communications with them). And given that we don't have a use-case for this in the product, I am leaning towards marking this one as out-of-scope. You're more than welcome to create your own [product icon theme](https://code.visualstudio.com/api/extension-guides/product-icon-theme) and contribute a [custom icon](https://code.visualstudio.com/api/extension-guides/product-icon-theme#icon-definitions) that includes these.
