### ISSUE TITLE
Add `symbol-comment`

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode-codicons#76]
**Is your icon request related to a problem? Please describe.**
For region markers and comment section ehaders in the outline tree.

**Describe the solution you'd like**
Add `symbol-comment` icon combining inner path of `symbol-string` and `comment`.

**Describe alternatives you've considered**
N/A.

**Comment by misolori** [comment]
Are you suggesting we do something like this?

<img width="205" alt="CleanShot 2021-08-19 at 12 37 20@2x" src="https://user-images.githubusercontent.com/35271042/130133159-46b214c0-c2b4-4a21-aab7-3054afee9db9.png">

**Comment by SNDST00M** [comment]
Looks great!

**Comment by misolori** [comment]
So this icon is the same concept our regular comment:

<img width="89" alt="CleanShot 2021-08-19 at 13 23 12@2x" src="https://user-images.githubusercontent.com/35271042/130138690-692ae502-35df-4c36-a460-b74db8537254.png">


Why would we need another one? We also have other similar ones:

<img width="101" alt="CleanShot 2021-08-19 at 13 22 20@2x" src="https://user-images.githubusercontent.com/35271042/130138609-51f8a06d-684d-4d7f-9b9f-33b1f30d8f66.png"> <img width="160" alt="CleanShot 2021-08-19 at 13 22 54@2x" src="https://user-images.githubusercontent.com/35271042/130138651-f3e93e00-e441-47a9-83e2-27e0fec1d2ef.png">

**Comment by SNDST00M** [comment]
Interesting, you make a very valid point!
I'd be happy with the first or last icon as the comment.

**Comment by SNDST00M** [comment]
(Unless you would like to add an alias? If and when vscode gives a `Comment` symbol kind)

**Comment by SNDST00M** [comment]
`symbol-comment` is the alias I was referring to
