### ISSUE TITLE
Request for `library-folder` icon

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-codicons#77]
**Is your icon request related to a problem? Please describe.**
I'm developing Java related extensions. Currently we have `library` icon to describe a library, it's pretty good, but when I just want to describe a folder which contains libraries, there is no proper icon exists. (I'd like to distinguish the library folder icon from the normal folder icon)

**Describe the solution you'd like**
IntelliJ IDEA has a proper library folder icon.
![dependencies](https://user-images.githubusercontent.com/45906942/127084317-3eeed371-bde3-4dcb-98c9-2eb3cbc1822c.png)
It helps to show the hieratical structure of project dependency. We can have a such icon combines a `folder` and a `library` to describe a `library folder` well.

**Comment by misolori** [comment]
<img width="133" alt="CleanShot 2021-08-19 at 15 10 28@2x" src="https://user-images.githubusercontent.com/35271042/130150934-557f81e1-1537-4eeb-a2e2-ded30f35c55e.png">

**Comment by CsCherrYY** [comment]
@misolori Looks perfect, thanks!

**Comment by jdneo** [comment]
@misolori Thank you for designing this icon!

![image](https://user-images.githubusercontent.com/6193897/132626554-4abcd0a0-de43-44ab-93ea-ebaa1b757bad.png)

**Comment by Eskibear** [comment]
Maven is also using the same icon! 
![image](https://user-images.githubusercontent.com/2351748/132631700-c587b2f3-6e54-4c93-830c-885e7b9fa31d.png)

**Comment by CsCherrYY** [comment]
for vscode-gradle, we have also applied this icon!
![Screenshot 2021-09-10 104021](https://user-images.githubusercontent.com/45906942/132790704-1642573b-c3a8-4b21-b2ea-296afca0c21e.png)
