### ISSUE TITLE
Add new icon for run all failed tests  

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-codicons#78]
Hey there! Now that there will be a "Test: Rerun Failed Tests" command, I was wondering if we could have a new official icon (perhaps updated to the vscode-icons repo, if it's not too much work) that we could display on the test explorer (only when there is at least one failed test in the view)? 

We have custom ones at https://github.com/microsoft/vscode-python/blob/main/resources/dark/run-failed-tests.svg and https://github.com/microsoft/vscode-python/blob/main/resources/light/run-failed-tests.svg, but we figured it'd be best to have something provided "officially" by VS Code

**Comment by misolori** [comment]
How about this?

<img width="162" alt="CleanShot 2021-08-16 at 11 02 09@2x" src="https://user-images.githubusercontent.com/35271042/129608877-b0ae215c-8dbf-42d4-8ee0-ccbb6e62f172.png">

This also maps with our other run icons:

<img width="662" alt="CleanShot 2021-08-16 at 11 02 27@2x" src="https://user-images.githubusercontent.com/35271042/129608913-65896de3-790f-4f22-b456-7b1cdceaa3ce.png">

**Comment by luabud** [comment]
@misolorio I love it! 

cc @karthiknadig

**Comment by misolori** [comment]
<img width="137" alt="CleanShot 2021-08-19 at 15 10 51@2x" src="https://user-images.githubusercontent.com/35271042/130150970-337c302f-977b-4466-930f-0e7146cde76f.png">
