### ISSUE TITLE
VSC Notebooks - Table of Contents

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-codicons#80]
Hope to get a version of this icon for table of contents in notebooks

https://iconcloud.design/search/filter/Full%20MDL2%20Assets/Full%20MDL2%20Assets/customlist/88014e748-c4094e9ea

![image](https://user-images.githubusercontent.com/19276747/130871525-1bbdb640-04fc-42ea-8aa6-121db0b39b32.png)

**Comment by misolori** [comment]
Can you use the `list-unordered` icon?

<img width="137" alt="CleanShot 2021-08-30 at 12 16 42@2x" src="https://user-images.githubusercontent.com/35271042/131392771-a73e38e1-b802-4238-8db0-a7211030e4c2.png">

**Comment by claudiaregio** [comment]
@misolori Sorry I totally missed this, yeah that looks super close!

**Comment by misolori** [comment]
Ok great, I’ll close this issue out then. Thanks!
