### ISSUE TITLE
`line-graph` and `pie-chart`

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode-codicons#81]
**Is your icon request related to a problem? Please describe.**
For numerical computing terminals and statistical webviews

**Describe the solution you'd like**
`line-graph` and `pie-chart` icon.
Sorta like these icons: https://materialdesignicons.com/tag/math

**Describe alternatives you've considered**
The current `chart` icon is only valid for box charts.

**Comment by misolori** [comment]
Added `graph-line`, `graph-scatter`, and `pie-chart`

<img width="510" alt="CleanShot 2021-09-24 at 10 26 14@2x" src="https://user-images.githubusercontent.com/35271042/134716290-681aed0e-da74-4159-9d43-a83edeaf3c4e.png">

<img width="151" alt="CleanShot 2021-09-24 at 10 15 47@2x" src="https://user-images.githubusercontent.com/35271042/134715111-020ed9bc-5484-4cc5-9333-a60396d5418d.png">

**Comment by SNDST00M** [comment]
Man those look amazing! Thanks
