### ISSUE TITLE
Refresh status icon

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-codicons#82]
Hi there! If this is the wrong repo to file this issue let me know and I can transfer/create a new one on the right repo 😊

We have an experiment running that displays an icon to refresh the Python test explorer, as this is a functionality we used to have on our old test explorer that everyone in the team said they missed when we were dogfooding:

 
![image](https://user-images.githubusercontent.com/45497113/132395962-b01b6117-5d0a-44f7-944f-a4648436fd04.png)

Once you click on it, we display a stop refresh icon, and we display a spinning icon next to it to indicate that the refresh is happening:

![image](https://user-images.githubusercontent.com/45497113/132396085-37c00fea-69fb-4316-afab-695e27452fad.png)

We were wondering if there might be a better way we can indicate that the refresh is happening without having a separate refresh icon just to indicate the status. We talked about the possibility of a "spinny stop refresh" icon, where the round arrow would spin and the solid square would remain still. We'd also love to hear other thoughts and ideas!

cc @karthiknadig

**Comment by misolori** [comment]
In search we use `search-stop` and use this pattern, which would apply here:


https://user-images.githubusercontent.com/35271042/132546685-92780c0e-37c6-4f54-9082-303138787ce3.mp4

I'd propose to create a refresh with a similar "stop" icon and leveraging the view to display "loading".

**Comment by luabud** [comment]
I like that proposal! @karthiknadig what do you think?

**Comment by karthiknadig** [comment]
When we run tests each test item gets a spinner, so I feel the discovery should also have a spinner. Since the discovery doesn't show progress in another way ( we don't even have a way to tell progress in some scenarios). Additionally, the blue progress indicator feels less visible in comparison with the spinner.

**Comment by karthiknadig** [comment]
I was thinking something like this:
![refresh-stop](https://user-images.githubusercontent.com/3840081/133185605-35de6621-7ed4-40c7-8eb8-fbb18d023219.gif)

**Comment by misolori** [comment]
Unfortunately those types of spinning icons aren't possible with our icons (that is two icons overlapped) we can only use a single icon to animate. Right now we only allow two icons that can animate: `loading` and `sync`. We recommend everyone to use `loading` when you are waiting for data to load/process and `sync` is when you need to have two connections send information back and forth.

> Additionally, the blue progress indicator feels less visible in comparison with the spinner.

The blue progress is a standard VS Code pattern that I don't think we want to try and re-invent the wheel for. It's fine if we want to find alternate icons to represent different states but in terms of spinning icons and showing progress, these two items are core patterns.

**Comment by misolori** [comment]
@luabud let me know what you want to do here. if we want to follow the pattern in search then I can add a beaker with a stop icon like:

<img width="176" alt="CleanShot 2021-09-24 at 09 20 46@2x" src="https://user-images.githubusercontent.com/35271042/134708361-fefa51a1-454d-43c7-a857-91a2f20448f5.png">

**Comment by karthiknadig** [comment]
I think this will work. Looks like Test UI has a way to show busy at each node level. So this should work.

**Comment by misolori** [comment]
Alright, I'll add this icon. Thanks for the feedback!

**Comment by misolori** [comment]
I've added `beaker-stop`:

<img width="271" alt="CleanShot 2021-09-24 at 09 47 52@2x" src="https://user-images.githubusercontent.com/35271042/134711785-10c837cc-0d68-4afe-927c-ea250da1f8a1.png">
