### ISSUE TITLE
`select-all` or `find-all`

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-codicons#83]
**Is your icon request related to a problem? Please describe.**
microsoft/vscode#7559

**Describe the solution you'd like**
An icon for multiple selections, but ideally associated with the `current` search icon - 🔍

**Describe alternatives you've considered**
Someone suggested `∀` which is a mathematical symbol and meaningless to most end users.

**Additional context**
There are several examples of this icon out there.

**Comment by meche-gh** [comment]
It's astute that this was opened. For anyone needing this icon, closest analogs that communicate this function are `expand-all` and `plus`. Hope this helps someone.
