### ISSUE TITLE
Installing version 0.0.23 throws an error

### ISSUE THREAD

**Issue by metonym** [microsoft/vscode-codicons#87]
**Describe the bug**
Attempting to install `@vscode/codicons` version 0.0.23 from NPM throws the following error:

```sh
command sh -c npx npm-force-resolutions
npm ERR! Error: ENOENT: no such file or directory, open './package-lock.json'
```

I've tried using both Yarn and NPM in a fresh project.

**To Reproduce**
1. Run `npm install @vscode/codicons@0.0.23` or `yarn add @vscode/codicons@0.0.23`

**Expected behavior**
The installation should not throw an error.

Installing version 0.0.22 works.

**Environment**
 - OS: Mac
 - VS Code Version 1.60.1

**Comment by misolori** [comment]
Thanks for the ping, let me check what is happening

**Comment by misolori** [comment]
Turns out we forgot to add `npm-force-resolutions` let me re-publish

**Comment by misolori** [comment]
For whatever reason npm did not like that package, have removed it and re-published. Please use `0.0.25`.

Fixed via https://github.com/microsoft/vscode-codicons/commit/4476b59e2764186d33b4d360f1d85f791df2d565
