### ISSUE TITLE
chrome-maximize and chrome-restore need to be updated for Windows 11

### ISSUE THREAD

**Issue by 1ctinus** [microsoft/vscode-codicons#90]
**Is your icon request related to a problem? Please describe.**
The problem is that the window decorations are in the style of Windows 10, which is inconsistent with Windows 11.

**Describe the solution you'd like**
Round chrome-maximize and chrome-restore.

**Describe alternatives you've considered**
I've considered trying to make a PR, but I have no SVG of the new windows 11 controls.

**Comment by misolori** [comment]
This will be tricky as those icons are used across other platforms that aren’t windows (Linux and Web). Will likely need to make windows specific ones.

**Comment by 1ctinus** [comment]
Most windows are rounded in most operating systems nowadays (GNOME, macOS, Windows 11), so I would say the change is appropriate.

**Comment by misolori** [comment]
Our iconography style uses bevel edges instead of rounded corners. It’s a stylistic choice we use regardless of the operating system.

**Comment by misolori** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/136132#issuecomment-956326104

> To solve this issue we will adopt window-controls-overlay and this should solve this issue as well.

As there will be no need for our icons to be updated.
