### ISSUE TITLE
Icon fonts not hidden to screen readers

### ISSUE THREAD

**Issue by anevins12** [microsoft/vscode-codicons#93]
**Describe the bug**
The demonstration code samples do not hide icons from screen readers.

**To Reproduce**
1. Go to the [demo](https://microsoft.github.io/vscode-codicons/dist/codicon.html).
2. Inspect the element containing the pseudo attribute.
3. Identify that the font icon is exposed in the accessibility tree, for instance, in Chrome as "StaticText "".

**Expected behavior**
The icon should be hidden from the accessibility tree so that it is not announced by screen readers. This can be achieved by adding `aria-hidden="true"` to the containing element.

**Comment by misolori** [comment]
The demo is a sample of how to use the icons in an HTML page, it's not intended to be used in production.

**Comment by anevins12** [comment]
I don't understand. The document is live and in production right now, as it's a Github web page. A Github web page is not exempt from screen reader support or accessibility support.

**Comment by misolori** [comment]
That's a fair point, this page isn't used in any of our vscode products and was meant to only be used as a demo. I'll work on adding the appropriate aria labels.
