### ISSUE TITLE
Icons seem shifted up a few pixels when used in terminals (at least on Linux)

### ISSUE THREAD

**Issue by ChristianChiarulli** [microsoft/vscode-codicons#94]
**Describe the bug**
Codicons seem to be shifted up a couple of pixels when used in Neovim on Linux. Tested on Kitty Terminal and Alacritty.

**To Reproduce**
1. Install kitty or alacritty (likely any terminal for linux)
2. install codicon font
3. use font for neovim or vim
4. observe the icon seems to be shifted up somewhat

**Expected behavior**
Codicons are more "flush" with the rest of the font

**Screenshots**
![image](https://user-images.githubusercontent.com/29136904/147411887-2d104013-ff70-4584-9446-ffcfa2508164.png)
^^ alacritty
![image](https://user-images.githubusercontent.com/29136904/147411917-3395d9b0-5d0e-4f16-8de1-90376361beff.png)
^^ kitty (Note the git branch icon which is from a patched nerdfont)

**Environment**
 - Linux

**Comment by misolori** [comment]
Codicons are designed at 16px so depending on what size you set them in your terminal they may appear differently. Not sure if we'd support this as the primary use case is in VS Code.

**Comment by ChristianChiarulli** [comment]
I was able to get my desired result by shifting the `viewBox` property down a bit. Not sure if there is a better way.

**Comment by misolori** [comment]
Thanks for the fork, will close this as mentioned in #97 that using this as a primary font is not recommended or supported since it is an icon font.
